[package]
name = "mos-pia-6520"
description = "MOS 6520 / Motorola 6821 Peripheral Interface Adapter"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "mos_pia_6520"
path = "src/lib.rs"

[dependencies]
serde = { workspace = true }

[lints]
workspace = true
