//! Fixture-free proof that these machines boot.
//!
//! The Master System and Game Gear declare no firmware — a cartridge is
//! all they need — so unlike almost every other machine here, "does it
//! boot" can be answered without a commercial ROM. `cart_boot.rs` beside
//! this file is `#[ignore]`d because it wants a real game; this runs
//! everywhere, on every push, forever.
//!
//! The cartridge is generated by
//! `test-data/sega/synthetic-cart/build-synthetic-cart.py` and contains no
//! code from any commercial image. It paints the backdrop a colour that
//! cannot appear unless the machine executed it: CRAM powers up as zeros,
//! so green means the reset vector was fetched, instructions ran, the I/O
//! ports decoded, the VDP registers took their writes, and a frame came
//! out. A machine that hangs produces black.
//!
//! The two machines reach the same colour by different routes. The Master
//! System's palette is 6-bit in one byte; the Game Gear's is 12-bit across
//! two. A single shared path would prove less.

use std::path::PathBuf;

use machine_sega_master_system::{Sms, SmsVariant};

/// Full green, opaque.
const EXPECTED: u32 = 0xFF00_FF00;

fn cart(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../test-data/sega/synthetic-cart")
        .join(name)
}

fn booted(name: &str, variant: SmsVariant) -> Sms {
    let rom = std::fs::read(cart(name))
        .unwrap_or_else(|err| panic!("synthetic cartridge {name} should be committed: {err}"));
    let mut machine = Sms::new(rom, variant);
    // Five frames: enough for the program to run and the display to be
    // enabled, few enough that a hang cannot be mistaken for patience.
    for _ in 0..5 {
        machine.run_frame();
    }
    machine
}

fn all_pixels(machine: &Sms) -> Option<u32> {
    let first = *machine.framebuffer().first()?;
    machine
        .framebuffer()
        .iter()
        .all(|&pixel| pixel == first)
        .then_some(first)
}

#[test]
fn the_master_system_boots_a_cartridge_and_paints_its_backdrop() {
    let machine = booted("master-system.sms", SmsVariant::SmsNtsc);

    assert_eq!(
        (machine.framebuffer_width(), machine.framebuffer_height()),
        (288, 240),
        "the Master System displays a television envelope"
    );
    assert_eq!(
        all_pixels(&machine),
        Some(EXPECTED),
        "the cartridge should have painted the whole display green; \
         black means it never ran"
    );
}

#[test]
fn the_game_gear_boots_a_cartridge_and_paints_its_backdrop() {
    let machine = booted("game-gear.gg", SmsVariant::GameGear);

    assert_eq!(
        (machine.framebuffer_width(), machine.framebuffer_height()),
        (160, 144),
        "the Game Gear displays its LCD, not a television (#1003)"
    );
    assert_eq!(
        all_pixels(&machine),
        Some(EXPECTED),
        "the cartridge should have painted the whole LCD green through the \
         Game Gear's 12-bit palette; black means it never ran"
    );
}

/// The check above is only worth having if it can fail. An empty cartridge
/// is a machine that fetches nothing useful, and it must not look like a
/// boot.
#[test]
fn an_empty_cartridge_does_not_look_like_a_boot() {
    let mut machine = Sms::new(vec![0; 32 * 1024], SmsVariant::SmsNtsc);
    for _ in 0..5 {
        machine.run_frame();
    }
    assert_ne!(
        all_pixels(&machine),
        Some(EXPECTED),
        "a cartridge that paints nothing must not pass the boot assertion"
    );
}
