[package]
name = "format-nintendo-nes-ines"
description = "iNES / NES 2.0 cartridge header parser + NES mapper trait and current wave-1 mapper implementations."
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
serde-big-array = { workspace = true }
