[package]
name = "mos-vic-ii"
description = "MOS 6569 PAL / 6567 NTSC VIC-II video chip for Commodore systems"
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
serde-big-array = { workspace = true }

[lints]
workspace = true
