[package]
name = "format-sinclair-zx-spectrum-z80"
description = ".z80 snapshot format parser for the ZX Spectrum"
edition.workspace = true
version = "0.2.0"
license.workspace = true
repository.workspace = true

[dependencies]
format-sinclair-zx-spectrum-snapshot = { path = "../format-sinclair-zx-spectrum-snapshot" }
