//! Fixture-free proof that the machine starts.
//!
//! The Atari 5200 needs its manufacturer's ROM to reach a prompt, and that ROM
//! cannot be copied to a public runner. So this asks the weaker question CI
//! *can* answer: put code this project wrote in the ROM socket, and see
//! whether the machine runs it.
//!
//! A pass proves the reset vector was fetched, the ROM is readable where the
//! memory map says it is, the CPU executed, GTIA took its register write,
//! and a frame reached the framebuffer. It does **not** prove the real
//! firmware boots — that claim belongs to the machines whose own ROMs may be
//! distributed, or which have a free reimplementation.
//!
//! The image is generated by
//! `test-data/synthetic-firmware/build-synthetic-firmware.py`, which also
//! builds a control image that spins without touching the hardware. Every
//! control renders black, which is where the expected colour below comes
//! from — measured against "never ran", not assumed.

use std::path::PathBuf;

use machine_atari_5200::{Atari5200, Atari5200Region};

/// What `COLBK = $44` renders. ANTIC's DMA is off at power-on, so with no
/// display list fetched the whole raster is the background register — this
/// is the one machine here whose frame comes out entirely uniform.
const BACKDROP: u32 = 0xFFB0_3C3C;

fn firmware(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../test-data/synthetic-firmware")
        .join(name)
}

#[test]
fn synthetic_firmware_runs_and_floods_the_display() {
    let bios = std::fs::read(firmware("atari-5200-bios.rom")).expect("bios image");
    let cart = vec![0xFFu8; 0x2000];

    let mut machine =
        Atari5200::new(cart, bios, Atari5200Region::Ntsc).expect("synthetic BIOS should init");
    for _ in 0..10 {
        machine.run_frame();
    }

    let framebuffer = machine.framebuffer();
    let first = *framebuffer.first().expect("non-empty framebuffer");
    assert_eq!(
        first, BACKDROP,
        "GTIA should show the backdrop the BIOS wrote"
    );
    assert!(
        framebuffer.iter().all(|&pixel| pixel == BACKDROP),
        "with DMA off the whole raster is the backdrop; found other colours"
    );
}

/// The control image spins without touching GTIA.
#[test]
fn the_control_image_renders_no_backdrop_at_all() {
    let bios = std::fs::read(firmware("atari-5200-bios-control.rom")).expect("control image");
    let cart = vec![0xFFu8; 0x2000];

    let mut machine =
        Atari5200::new(cart, bios, Atari5200Region::Ntsc).expect("control BIOS should init");
    for _ in 0..10 {
        machine.run_frame();
    }

    assert_eq!(
        machine
            .framebuffer()
            .iter()
            .filter(|&&p| p == BACKDROP)
            .count(),
        0,
        "a machine that ran no firmware must not show the firmware's colour"
    );
}
