//! Single-step validation harness for the 68881/2 FPU against a Musashi
//! oracle corpus.
//!
//! The fixtures come from `m68k-test-gen --fp`, which drives Musashi's
//! on-chip 68040 FPU as the reference. Musashi uses generic-Berkeley
//! SoftFloat; our `floatx80` core is now the 68881/2's SOFTFLOAT_68K
//! (re-based on WinUAE's silicon-validated port), so the two diverge on the
//! 68k special-value encodings (created NaN/∞, denormal exponent/retention,
//! NaN propagation). The authoritative FP-value oracle is therefore the
//! WinUAE C-diff (`crates/motorola-68k-common/validation/run_fpsp.sh`); this
//! corpus validates the rest of the instruction path (decode, operand fetch,
//! FPSR CC, integer state) with the known created-value differences
//! normalised in `compare_final`. See `knowledge/decisions/
//! fpu-softfloat-port.md`.
//!
//! Each fixture covers one register-to-register FPgen instruction
//! (FADD/FSUB/FMUL/FDIV/FCMP/FSQRT/FINT/FINTRZ/FMOVE/FABS/FNEG/FTST) with
//! random normalized-finite operands and FPCR = 0 (round-to-nearest,
//! extended precision).
//!
//! What is compared: the eight FP data registers (full 80-bit values),
//! the FPSR condition-code byte (bits 27-24: N/Z/I/NAN), and the integer
//! architectural state the instruction advances (PC, SR, A/D registers).
//! What is deferred: the FPSR exception/accrued bytes and FPIAR — our
//! core carries `TODO(FPSR)` for exception reporting, so those bits are
//! out of scope until that lands.
//!
//! Default corpus root (generated by `m68k-test-gen --cpu 68040 --fp --all`):
//!   `assets/test-suites/m68k-generated/m68040-fpu/v1/`
//! or the in-repo `test-data/m68k-68040-fpu/v1/`. Override with
//! `M68020_FPU_TEST_DATA`.
//!
//! Skipped under normal `cargo test`. Run explicitly with:
//!
//! ```sh
//! cargo test -p motorola-68020 --test fpu_corpus -- --ignored --nocapture
//! ```

#![allow(clippy::unwrap_used)]

use std::collections::HashMap;
use std::fs::File;
use std::io::Read;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use motorola_68000::bus::{BusStatus, FunctionCode, interrupt_acknowledge_level};
use motorola_68000::cpu::State;
use motorola_68000::registers::FpReg;
use motorola_68020::Cpu68020;

// ─── Fixture schema (mirrors m68k-test-gen / testcase.rs) ─────────

#[derive(Debug, Clone, Serialize, Deserialize)]
struct TestFile {
    cpu: String,
    instruction: String,
    tests: Vec<TestCase>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct TestCase {
    name: String,
    initial: CpuState,
    final_state: CpuState,
    cycles: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct CpuState {
    d: [u32; 8],
    a: [u32; 7],
    usp: u32,
    ssp: u32,
    sr: u16,
    pc: u32,
    prefetch: [u16; 2],
    ram: Vec<(u32, u8)>,
    #[serde(default)]
    msp: u32,
    #[serde(default)]
    vbr: u32,
    #[serde(default)]
    cacr: u32,
    #[serde(default)]
    caar: u32,
    // 68881/2 FPU state. The fixtures are named-map encoded, so any of
    // these may be absent (defaulting to zero) without shifting the rest.
    #[serde(default)]
    fp: [(u16, u64); 8],
    #[serde(default)]
    fpcr: u32,
    #[serde(default)]
    fpsr: u32,
    #[serde(default)]
    fpiar: u32,
}

// ─── Sparse memory ────────────────────────────────────────────────

struct SparseMem {
    bytes: HashMap<u32, u8>,
}

impl SparseMem {
    fn new() -> Self {
        Self {
            bytes: HashMap::new(),
        }
    }

    fn load_ram(&mut self, ram: &[(u32, u8)]) {
        for (addr, value) in ram {
            self.bytes.insert(addr & 0xFF_FFFF, *value);
        }
    }

    fn read_byte(&self, addr: u32) -> u8 {
        *self.bytes.get(&(addr & 0xFF_FFFF)).unwrap_or(&0)
    }

    fn read_word(&self, addr: u32) -> u16 {
        let a = addr & 0xFF_FFFF;
        (u16::from(self.read_byte(a)) << 8) | u16::from(self.read_byte(a + 1))
    }

    fn write_byte(&mut self, addr: u32, val: u8) {
        self.bytes.insert(addr & 0xFF_FFFF, val);
    }

    fn write_word(&mut self, addr: u32, val: u16) {
        let a = addr & 0xFF_FFFF;
        self.write_byte(a, (val >> 8) as u8);
        self.write_byte(a + 1, val as u8);
    }
}

// ─── Fixture loading ──────────────────────────────────────────────

fn candidate_fixture_roots() -> Vec<PathBuf> {
    let mut roots = Vec::new();
    if let Ok(path) = std::env::var("M68020_FPU_TEST_DATA") {
        roots.push(PathBuf::from(path));
    }
    if let Ok(home) = std::env::var("HOME") {
        roots.push(
            PathBuf::from(&home)
                .join("Projects/198x/assets/test-suites/m68k-generated/m68040-fpu/v1"),
        );
    }
    // In-repo default written by `m68k-test-gen --fp` (repo-root test-data/).
    let repo_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .map(Path::to_path_buf);
    if let Some(root) = repo_root {
        roots.push(root.join("test-data/m68k-68040-fpu/v1"));
    }
    roots
}

fn fixture_root() -> Option<PathBuf> {
    candidate_fixture_roots().into_iter().find(|p| p.is_dir())
}

fn load_fixture(path: &Path) -> Option<TestFile> {
    let mut file = File::open(path).ok()?;
    let mut buf = Vec::new();
    file.read_to_end(&mut buf).ok()?;
    rmp_serde::from_slice(&buf).ok()
}

// ─── CPU state setup ──────────────────────────────────────────────

fn apply_initial(cpu: &mut Cpu68020, mem: &mut SparseMem, initial: &CpuState) {
    cpu.regs.d = initial.d;
    cpu.regs.a = initial.a;
    cpu.regs.usp = initial.usp;
    cpu.regs.ssp = initial.ssp;
    cpu.regs.msp = initial.msp;
    cpu.regs.sr = initial.sr;
    cpu.regs.vbr = initial.vbr;
    cpu.regs.cacr = initial.cacr;
    cpu.regs.caar = initial.caar;

    for (slot, &(high, low)) in cpu.regs.fp.iter_mut().zip(initial.fp.iter()) {
        *slot = FpReg::new(high, low);
    }
    cpu.regs.fpcr = initial.fpcr;
    cpu.regs.fpsr = initial.fpsr;
    cpu.regs.fpiar = initial.fpiar;

    // The opcode + extension word were poked into RAM by the generator;
    // read them straight back as IR/IRC (Musashi's IR after reset is stale).
    let pc = initial.pc;
    let pf0 = mem.read_word(pc);
    let pf1 = mem.read_word(pc.wrapping_add(2));

    cpu.regs.pc = pc.wrapping_add(4);
    cpu.setup_prefetch(pf0, pf1);
}

// ─── Bus service ──────────────────────────────────────────────────

fn service_bus(cpu: &mut Cpu68020, mem: &mut SparseMem) {
    if let State::BusCycle {
        addr,
        fc,
        is_read,
        is_word,
        data,
        cycle_count,
        ..
    } = &cpu.state
    {
        if *cycle_count >= 3 {
            if *fc == FunctionCode::InterruptAck {
                let acknowledged_level = interrupt_acknowledge_level(*addr);
                cpu.bus_status = BusStatus::Ready(24 + u16::from(acknowledged_level));
            } else if *is_read {
                let val = if *is_word {
                    mem.read_word(*addr)
                } else {
                    u16::from(mem.read_byte(*addr))
                };
                cpu.bus_status = BusStatus::Ready(val);
            } else {
                let val = data.unwrap_or(0);
                if *is_word {
                    mem.write_word(*addr, val);
                } else {
                    mem.write_byte(*addr, val as u8);
                }
                cpu.bus_status = BusStatus::Ready(0);
            }
        } else {
            cpu.bus_status = BusStatus::Wait;
        }
    } else {
        cpu.bus_status = BusStatus::Wait;
    }
}

fn run_one_instruction(cpu: &mut Cpu68020, mem: &mut SparseMem) -> bool {
    let start_count = cpu.instruction_starts;
    // FMOVEM of 8 registers is ~96 byte bus cycles; give the slowest
    // instruction ample headroom (other ops exit early on the start count).
    for _ in 0..3000 {
        service_bus(cpu, mem);
        cpu.tick();
        if cpu.instruction_starts > start_count {
            return true;
        }
    }
    false
}

// ─── State comparison ─────────────────────────────────────────────

#[derive(Default, Debug)]
struct Mismatch {
    field: String,
    expected: String,
    actual: String,
}

fn compare_final(cpu: &Cpu68020, mem: &SparseMem, final_state: &CpuState) -> Vec<Mismatch> {
    let mut v = Vec::new();

    // FP data registers — the heart of the comparison.
    //
    // The Musashi oracle is generic-Berkeley SoftFloat; our port is now the
    // 68881/2's SOFTFLOAT_68K, so the two deliberately diverge on the 68k
    // special-value encodings. The authoritative FP-value check is the WinUAE
    // C-diff (`validation/run_fpsp.sh`); here we normalise the known created-
    // value differences so this corpus still validates the instruction path
    // (decode, operand fetch, FPSR CC, integer state advancement):
    //   * created NaN: 68k clears the sign bit ($7FFF:FFFF…), Berkeley sets it.
    //   * created ∞:   68k clears the integer bit ($7FFF:0 / $FFFF:0), Berkeley
    //                  sets it ($7FFF:8000… / $FFFF:8000…).
    let nan_equiv = |a: (u16, u64), b: (u16, u64)| {
        a == (0x7FFF, 0xFFFF_FFFF_FFFF_FFFF) && b == (0xFFFF, 0xFFFF_FFFF_FFFF_FFFF)
    };
    let inf_equiv = |a: (u16, u64), b: (u16, u64)| {
        (a.0 & 0x7FFF) == 0x7FFF && a.1 == 0 && a.0 == b.0 && b.1 == 0x8000_0000_0000_0000
    };
    for i in 0..8 {
        let got = cpu.regs.fp[i];
        let (eh, el) = final_state.fp[i];
        let g = (got.high, got.low);
        let e = (eh, el);
        if nan_equiv(g, e) || inf_equiv(g, e) {
            continue;
        }
        if got.high != eh || got.low != el {
            v.push(Mismatch {
                field: format!("fp{i}"),
                expected: format!("{eh:04X}:{el:016X}"),
                actual: format!("{:04X}:{:016X}", got.high, got.low),
            });
        }
    }

    // FPSR condition-code byte (bits 27-24): N, Z, I, NAN. Exception and
    // accrued bytes are deferred (TODO(FPSR)).
    let got_cc = (cpu.regs.fpsr >> 24) & 0x0F;
    let exp_cc = (final_state.fpsr >> 24) & 0x0F;
    if got_cc != exp_cc {
        v.push(Mismatch {
            field: "fpcc".into(),
            expected: format!("{exp_cc:01X}"),
            actual: format!("{got_cc:01X}"),
        });
    }

    // Integer architectural state the instruction advances.
    if cpu.instr_start_pc != final_state.pc {
        v.push(Mismatch {
            field: "pc".into(),
            expected: format!("${:08X}", final_state.pc),
            actual: format!("${:08X}", cpu.instr_start_pc),
        });
    }
    if cpu.regs.sr != final_state.sr {
        v.push(Mismatch {
            field: "sr".into(),
            expected: format!("${:04X}", final_state.sr),
            actual: format!("${:04X}", cpu.regs.sr),
        });
    }
    for (field, actual, expected) in [
        ("usp", cpu.regs.usp, final_state.usp),
        ("ssp", cpu.regs.ssp, final_state.ssp),
        ("msp", cpu.regs.msp, final_state.msp),
        ("vbr", cpu.regs.vbr, final_state.vbr),
        ("cacr", cpu.regs.cacr, final_state.cacr),
        ("caar", cpu.regs.caar, final_state.caar),
    ] {
        if actual != expected {
            v.push(Mismatch {
                field: field.into(),
                expected: format!("${expected:08X}"),
                actual: format!("${actual:08X}"),
            });
        }
    }
    for i in 0..8 {
        if cpu.regs.d[i] != final_state.d[i] {
            v.push(Mismatch {
                field: format!("d{i}"),
                expected: format!("${:08X}", final_state.d[i]),
                actual: format!("${:08X}", cpu.regs.d[i]),
            });
        }
    }
    for i in 0..7 {
        if cpu.regs.a[i] != final_state.a[i] {
            v.push(Mismatch {
                field: format!("a{i}"),
                expected: format!("${:08X}", final_state.a[i]),
                actual: format!("${:08X}", cpu.regs.a[i]),
            });
        }
    }

    // Memory the instruction wrote (FMOVE FPn → (An) stores).
    for (addr, expected) in &final_state.ram {
        let actual = mem.read_byte(*addr);
        if actual != *expected {
            v.push(Mismatch {
                field: format!("mem[${addr:06X}]"),
                expected: format!("${expected:02X}"),
                actual: format!("${actual:02X}"),
            });
        }
    }

    v
}

// ─── Per-fixture runner ────────────────────────────────────────────

struct FixtureResult {
    name: String,
    total: usize,
    passed: usize,
    first_fail: Option<(String, Vec<Mismatch>)>,
}

fn run_fixture(path: &Path) -> Option<FixtureResult> {
    let file = load_fixture(path)?;
    let name = path
        .file_name()
        .unwrap()
        .to_string_lossy()
        .trim_end_matches(".msgpack")
        .to_string();

    let mut passed = 0;
    let mut first_fail: Option<(String, Vec<Mismatch>)> = None;

    for test in &file.tests {
        let mut cpu = Cpu68020::new();
        cpu.set_fpu_present(true); // attach the 68881/2 coprocessor
        let mut mem = SparseMem::new();
        mem.load_ram(&test.initial.ram);
        apply_initial(&mut cpu, &mut mem, &test.initial);

        if !run_one_instruction(&mut cpu, &mut mem) {
            if first_fail.is_none() {
                first_fail = Some((
                    test.name.clone(),
                    vec![Mismatch {
                        field: "run".into(),
                        expected: "1 instruction".into(),
                        actual: "timeout".into(),
                    }],
                ));
            }
            continue;
        }

        let mismatches = compare_final(&cpu, &mem, &test.final_state);
        if mismatches.is_empty() {
            passed += 1;
        } else if first_fail.is_none() {
            first_fail = Some((test.name.clone(), mismatches));
        }
    }

    Some(FixtureResult {
        name,
        total: file.tests.len(),
        passed,
        first_fail,
    })
}

fn print_result(r: &FixtureResult) {
    let rate = if r.total > 0 {
        (r.passed as f64 / r.total as f64) * 100.0
    } else {
        0.0
    };
    println!(
        "  {:<10} {:>6}/{:<6} ({:>6.2}%)",
        r.name, r.passed, r.total, rate
    );
    if let Some((case, mismatches)) = &r.first_fail {
        println!("    first fail: {case}");
        for m in mismatches.iter().take(6) {
            println!(
                "      {:<10} expected={:<24} actual={}",
                m.field, m.expected, m.actual
            );
        }
        if mismatches.len() > 6 {
            println!("      ... and {} more", mismatches.len() - 6);
        }
    }
}

// ─── Tests ─────────────────────────────────────────────────────────

/// Full FP corpus sweep: per-instruction pass rate plus a total.
#[test]
#[ignore]
fn fpu_corpus_full_sweep() {
    let Some(root) = fixture_root() else {
        emu198x_test_skip::skip!("no FP corpus directory found");
    };

    let mut entries: Vec<PathBuf> = std::fs::read_dir(&root)
        .expect("read_dir")
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| {
            p.file_name()
                .map(|n| n.to_string_lossy().ends_with(".msgpack"))
                .unwrap_or(false)
        })
        .collect();
    entries.sort();

    println!();
    println!(
        "68881/2 FP corpus ({} fixtures) at {}:",
        entries.len(),
        root.display()
    );

    let mut total_passed = 0usize;
    let mut total_tests = 0usize;
    let mut fully_passing = 0usize;

    for path in &entries {
        let Some(r) = run_fixture(path) else {
            continue;
        };
        print_result(&r);
        total_passed += r.passed;
        total_tests += r.total;
        if r.passed == r.total {
            fully_passing += 1;
        }
    }

    println!();
    let rate = if total_tests > 0 {
        (total_passed as f64 / total_tests as f64) * 100.0
    } else {
        0.0
    };
    println!("FP TOTAL: {total_passed}/{total_tests} ({rate:.2}%)");
    println!("  fully passing: {fully_passing} / {}", entries.len());
}

/// Smoke test: FADD must validate. If this fails, the harness wiring
/// (deserialiser, FP setup, FPCC compare) is broken — don't chase the
/// full sweep.
#[test]
#[ignore]
fn fpu_corpus_fadd_smoke() {
    let Some(root) = fixture_root() else {
        emu198x_test_skip::skip!("no FP corpus directory found");
    };
    let path = root.join("FADD.msgpack");
    if !path.exists() {
        emu198x_test_skip::skip!("Skipping: {} not found", path.display());
    }

    let r = run_fixture(&path).expect("FADD fixture loads");
    println!();
    print_result(&r);
    assert!(r.total > 0, "FADD fixture should have tests");
}
