//! Inherited-subset cross-check against real 68000 hardware.
//!
//! Runs the upstream Tom Harte SingleStepTests/680x0 corpus —
//! generated by single-stepping a *physical* 68000 — through the
//! `Cpu68020` wrapper. Most of the 68020 ISA is inherited verbatim
//! from the 68000; this harness verifies the variant wrapper hasn't
//! accidentally broken that inherited behaviour.
//!
//! See [`knowledge/decisions/m68k-test-oracle-strategy.md`] for the
//! cross-validation rationale: the m68k-test-gen 68020 corpus is
//! Musashi-driven, so it can't catch Musashi-vs-real-hw divergences.
//! This harness, using the 68000 real-hw oracle, can.
//!
//! Adapted from `motorola-68000/tests/tom_harte.rs` — same fixture
//! format, sparse-memory harness, and bus-cycle service routine,
//! just pointed at `Cpu68020` instead of `Cpu68000`.
//!
//! Default corpus root:
//!   `~/Projects/198x/assets/test-suites/processor-tests/680x0/68000/v1/`
//!
//! Override with `EMU198X_68000_TOM_HARTE_ROOT`.
//!
//! # Expected divergence
//!
//! The following fixtures are skipped because their behaviour
//! legitimately differs between real 68000 hardware and the 68020
//! variant — they are not regressions:
//!
//! - **`ABCD` / `SBCD` / `NBCD`** — Musashi-style "undefined V"
//!   flag, enabled by `variant_musashi_bcd_v` on the 68020 wrapper.
//! - **`DIVU.W` / `DIVS.W`** overflow cases — Musashi preserves C
//!   on overflow; real hardware clears it (`variant_musashi_div_overflow`).
//! - **`MOVE from SR`** — non-privileged on the 68000, privileged
//!   on the 68020+. Any test in user mode raises a different trap
//!   on the 68020, with a different frame format.
//! - **Exception-bearing tests** that take a group-1/2 trap during
//!   the fixture: the 68020 pushes either an 8-byte Format `$0`
//!   frame (for TRAP / BKPT) or a 12-byte Format `$2` frame (for
//!   CHK / divide-by-zero / TRAPV — see
//!   `variant_format2_vectors`), whereas the 68000 pushes a 6-byte
//!   frame. Affects `CHK`, `TRAP`, `TRAPV`, `BKPT`, and the
//!   zero-divisor cases of `DIVU.W` / `DIVS.W`.
//! - **`RTE`** — the 68000 pops a 6-byte frame; the 68020 pops an
//!   8-byte frame (Format `$0`) or 12-byte (`$2`) frame.
//! - **`MOVEtoSR` / `ORItoSR` / `EORItoSR` / `ANDItoSR`** — the
//!   68020 widens the SR write mask to include the M-flag (bit
//!   12). When the source value or initial SR has the M-bit set,
//!   the 68000 corpus expects it to be masked out; the 68020
//!   preserves it. Documented as `variant_extended_sr_writes`.
//! - **Per-case indexed-addressing skips** (name contains "(d8,"):
//!   the brief extension word's scale field (bits 10-9) is "don't
//!   care" on the 68000 but `*1/*2/*4/*8` on the 68020+. The 68000
//!   corpus's random extension words contain non-zero scale bits
//!   that 68020 EA computation honours, producing a different
//!   effective address from real 68000 hardware. This is
//!   `variant_scaled_index` working as intended.

#![allow(clippy::unwrap_used)]

use std::collections::HashMap;
use std::fs::File;
use std::path::{Path, PathBuf};

use flate2::read::GzDecoder;
use serde_json::Value;

use motorola_68000::bus::{BusStatus, FunctionCode};
use motorola_68000::cpu::State;
use motorola_68020::Cpu68020;

// ─── Sparse memory ────────────────────────────────────────────────

struct SparseMem {
    bytes: HashMap<u32, u8>,
}

impl SparseMem {
    fn new() -> Self {
        Self {
            bytes: HashMap::new(),
        }
    }

    fn load_ram(&mut self, ram: &[Value]) {
        for entry in ram {
            let pair = entry.as_array().expect("ram entry is array");
            let addr = pair[0].as_u64().expect("ram addr") as u32;
            let value = pair[1].as_u64().expect("ram value") as u8;
            self.bytes.insert(addr & 0xFF_FFFF, value);
        }
    }

    fn read_byte(&self, addr: u32) -> u8 {
        *self.bytes.get(&(addr & 0xFF_FFFF)).unwrap_or(&0)
    }

    fn read_word(&self, addr: u32) -> u16 {
        let a = addr & 0xFF_FFFE;
        (u16::from(self.read_byte(a)) << 8) | u16::from(self.read_byte(a + 1))
    }

    fn write_byte(&mut self, addr: u32, val: u8) {
        self.bytes.insert(addr & 0xFF_FFFF, val);
    }

    fn write_word(&mut self, addr: u32, val: u16) {
        let a = addr & 0xFF_FFFE;
        self.write_byte(a, (val >> 8) as u8);
        self.write_byte(a + 1, val as u8);
    }
}

// ─── Fixture loading ──────────────────────────────────────────────

fn fixture_root() -> PathBuf {
    let home = std::env::var("HOME").expect("HOME set");
    let home = PathBuf::from(home);
    if let Ok(path) = std::env::var("EMU198X_68000_TOM_HARTE_ROOT") {
        let p = PathBuf::from(path);
        if p.is_dir() {
            return p;
        }
    }
    home.join("Projects/198x/assets/test-suites/processor-tests/680x0/68000/v1")
}

fn load_fixture(path: &Path) -> Option<Vec<Value>> {
    let file = File::open(path).ok()?;
    let gz = GzDecoder::new(file);
    let parsed: Value = serde_json::from_reader(gz).ok()?;
    Some(parsed.as_array()?.clone())
}

// ─── CPU state setup ──────────────────────────────────────────────

fn apply_initial(cpu: &mut Cpu68020, mem: &mut SparseMem, initial: &Value) {
    let o = initial.as_object().expect("initial is object");
    for i in 0..8 {
        cpu.regs.d[i] = o[&format!("d{i}")].as_u64().expect("dN") as u32;
    }
    for i in 0..7 {
        cpu.regs.a[i] = o[&format!("a{i}")].as_u64().expect("aN") as u32;
    }
    cpu.regs.usp = o["usp"].as_u64().expect("usp") as u32;
    cpu.regs.ssp = o["ssp"].as_u64().expect("ssp") as u32;
    cpu.regs.sr = o["sr"].as_u64().expect("sr") as u16;
    let pc = o["pc"].as_u64().expect("pc") as u32;

    let pq = o["prefetch"].as_array().expect("prefetch array");
    let pf0 = pq[0].as_u64().expect("prefetch0") as u16;
    let pf1 = pq[1].as_u64().expect("prefetch1") as u16;
    mem.write_word(pc, pf0);
    mem.write_word(pc.wrapping_add(2), pf1);

    cpu.regs.pc = pc.wrapping_add(4);
    cpu.setup_prefetch(pf0, pf1);
}

fn service_bus(cpu: &mut Cpu68020, mem: &mut SparseMem) {
    if let State::BusCycle {
        addr,
        fc,
        is_read,
        is_word,
        data,
        cycle_count,
        ..
    } = &cpu.state
    {
        if *cycle_count >= 3 {
            if *fc == FunctionCode::InterruptAck {
                cpu.bus_status = BusStatus::Ready(24 + u16::from(cpu.ipl));
            } else if *is_read {
                let val = if *is_word {
                    mem.read_word(*addr)
                } else {
                    u16::from(mem.read_byte(*addr))
                };
                cpu.bus_status = BusStatus::Ready(val);
            } else {
                let val = data.unwrap_or(0);
                if *is_word {
                    mem.write_word(*addr, val);
                } else {
                    mem.write_byte(*addr, val as u8);
                }
                cpu.bus_status = BusStatus::Ready(0);
            }
        } else {
            cpu.bus_status = BusStatus::Wait;
        }
    } else {
        cpu.bus_status = BusStatus::Wait;
    }
}

fn run_one_instruction(cpu: &mut Cpu68020, mem: &mut SparseMem) -> bool {
    let start_count = cpu.instruction_starts;
    for _ in 0..400 {
        service_bus(cpu, mem);
        cpu.tick();
        if cpu.instruction_starts > start_count {
            return true;
        }
    }
    false
}

// ─── State comparison ─────────────────────────────────────────────

fn matches_final(cpu: &Cpu68020, mem: &SparseMem, final_state: &Value) -> bool {
    let o = final_state.as_object().expect("final is object");
    for i in 0..8 {
        if cpu.regs.d[i] != o[&format!("d{i}")].as_u64().unwrap() as u32 {
            return false;
        }
    }
    for i in 0..7 {
        if cpu.regs.a[i] != o[&format!("a{i}")].as_u64().unwrap() as u32 {
            return false;
        }
    }
    if cpu.regs.usp != o["usp"].as_u64().unwrap() as u32 {
        return false;
    }
    if cpu.regs.ssp != o["ssp"].as_u64().unwrap() as u32 {
        return false;
    }
    if cpu.instr_start_pc != o["pc"].as_u64().unwrap() as u32 {
        return false;
    }
    if cpu.regs.sr != o["sr"].as_u64().unwrap() as u16 {
        return false;
    }
    for entry in o["ram"].as_array().unwrap() {
        let pair = entry.as_array().unwrap();
        let addr = pair[0].as_u64().unwrap() as u32;
        let expected = pair[1].as_u64().unwrap() as u8;
        if mem.read_byte(addr) != expected {
            return false;
        }
    }
    true
}

// ─── Expected-divergence fixture list ─────────────────────────────

/// Known-invalid fixture rows in the upstream corpus. The 68000
/// harness skips the same names — these are corpus bugs, not CPU
/// bugs (the "expected final D2" mutates bits a byte operation
/// can't touch).
fn is_known_invalid_case(case_name: &str) -> bool {
    matches!(
        case_name,
        "e502 [ASL.b Q, D2] 1583" | "e502 [ASL.b Q, D2] 1761"
    )
}

/// Per-case skip: 68020 honours the brief-extension-word scale
/// field (bits 10-9) that real 68000 hardware ignores, so any
/// test whose disassembled name uses indexed addressing has a
/// real-hw / 68020 EA divergence by design. The corpus name
/// includes the disassembly snippet — `"(d8, A0, Xn)"` or
/// `"(d8, PC, Xn)"` — so substring-matching on `"(d8,"` is enough.
fn is_indexed_addressing_case(case_name: &str) -> bool {
    case_name.contains("(d8,")
}

/// Fixtures whose behaviour legitimately differs between real
/// 68000 hardware and the 68020. Skipped entirely from the pass-rate
/// total because they're not regressions.
fn is_expected_divergent_fixture(name: &str) -> bool {
    matches!(
        name,
        // BCD V flag (variant_musashi_bcd_v).
        "ABCD" | "SBCD" | "NBCD"
            // DIV: overflow path differs (variant_musashi_div_overflow);
            // zero-divisor path differs in frame format.
            | "DIVU" | "DIVS"
            // Frame-format differences (6-byte vs 8-byte) when the
            // fixture triggers a group-1/2 exception.
            | "CHK" | "TRAP" | "TRAPV" | "BKPT" | "RTE" | "RTR"
            // MOVE from SR — non-privileged on 68000, privileged on 68020+.
            | "MOVEfromSR"
            // SR-write instructions where the 68020 preserves the
            // M-flag (bit 12) but the 68000 corpus expects it
            // masked out. variant_extended_sr_writes.
            | "MOVEtoSR" | "ORItoSR" | "ANDItoSR" | "EORItoSR" // 68020+ exception frame contains a Format/Vector word
                                                               // that the 68000 corpus's MOVEM (write to stack via TRAP)
                                                               // and similar context-saves don't match.
                                                               //
                                                               // Note: MOVEM itself isn't divergent at the ISA level;
                                                               // any failure here would be a regression. Not skipped.
    )
}

// ─── Test ─────────────────────────────────────────────────────────

#[test]
#[ignore]
fn inherited_subset_passes_real_hw_68000_corpus() {
    let root = fixture_root();
    if !root.exists() {
        eprintln!("Skipping: fixture dir not found at {}", root.display());
        return;
    }

    let mut entries: Vec<PathBuf> = std::fs::read_dir(&root)
        .expect("read_dir")
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| {
            p.file_name()
                .map(|n| n.to_string_lossy().ends_with(".json.gz"))
                .unwrap_or(false)
        })
        .collect();
    entries.sort();

    println!();
    println!(
        "68020 inherited-subset cross-check against real-68000 corpus ({} fixtures total):",
        entries.len()
    );

    let mut total_passed = 0usize;
    let mut total_tests = 0usize;
    let mut skipped_fixtures = 0usize;
    let mut regressions: Vec<(String, usize, usize, String)> = Vec::new();

    for path in &entries {
        let fixture_name = path
            .file_name()
            .unwrap()
            .to_string_lossy()
            .trim_end_matches(".json.gz")
            .to_string();
        let base_name = fixture_name
            .split('_')
            .next()
            .unwrap_or(&fixture_name)
            .split('.')
            .next()
            .unwrap_or(&fixture_name);

        if is_expected_divergent_fixture(base_name) {
            skipped_fixtures += 1;
            continue;
        }

        let Some(tests) = load_fixture(path) else {
            continue;
        };
        let mut passed = 0usize;
        let mut skipped_cases = 0usize;
        let mut first_fail: Option<String> = None;
        for test in &tests {
            let t = test.as_object().unwrap();
            let case_name = t["name"].as_str().unwrap_or("?").to_string();
            if is_known_invalid_case(&case_name) || is_indexed_addressing_case(&case_name) {
                skipped_cases += 1;
                continue;
            }
            let initial = &t["initial"];
            let final_state = &t["final"];

            let mut cpu = Cpu68020::new();
            let mut mem = SparseMem::new();
            mem.load_ram(initial["ram"].as_array().unwrap());
            apply_initial(&mut cpu, &mut mem, initial);

            if !run_one_instruction(&mut cpu, &mut mem) {
                if first_fail.is_none() {
                    first_fail = Some(format!("{case_name} (timeout)"));
                }
                continue;
            }
            if matches_final(&cpu, &mem, final_state) {
                passed += 1;
            } else if first_fail.is_none() {
                first_fail = Some(case_name);
            }
        }
        let counted = tests.len() - skipped_cases;
        total_passed += passed;
        total_tests += counted;

        if passed != counted {
            regressions.push((
                fixture_name,
                passed,
                counted,
                first_fail.unwrap_or_else(|| "?".into()),
            ));
        }
    }

    let rate = if total_tests > 0 {
        (total_passed as f64 / total_tests as f64) * 100.0
    } else {
        0.0
    };
    println!();
    println!(
        "INHERITED SUBSET: {}/{} ({:.4}%) across {} fixtures",
        total_passed,
        total_tests,
        rate,
        entries.len() - skipped_fixtures,
    );
    println!("  expected-divergent fixtures skipped: {skipped_fixtures}");
    if !regressions.is_empty() {
        println!();
        println!("Unexpected regressions ({}):", regressions.len());
        for (name, passed, total, first_fail) in &regressions {
            let pct = (*passed as f64 / *total as f64) * 100.0;
            println!(
                "  {:<24} {:>5}/{:<5} ({:>5.1}%)  first fail: {first_fail}",
                name, passed, total, pct
            );
        }
    }

    assert!(
        regressions.is_empty(),
        "The 68020 wrapper regressed on {} inherited-subset fixture(s) — see report above. \
         These are 68000 instructions that the 68020 inherits verbatim; failures here are real \
         regressions, not Musashi/real-hw divergence (those fixtures are pre-skipped).",
        regressions.len()
    );
}
