//! Fixture-free proof that the machine starts.
//!
//! The PET needs its manufacturer's ROMs to reach a prompt, and they cannot
//! be copied to a public runner. So this asks the weaker question CI *can*
//! answer: put code this project wrote in the ROM socket, and see whether
//! the machine runs it. It does **not** prove the real firmware boots.
//!
//! ## The PET is monochrome, so the signal is character output
//!
//! There is no colour to flood. Instead the synthetic character ROM defines
//! **glyph 0 as blank and glyph 1 as solid**, and the KERNAL fills screen
//! RAM at `$8000` with glyph 1.
//!
//! That split is the load-bearing part of the design. A character ROM whose
//! every glyph was solid would light the screen without the CPU doing
//! anything at all, and this test would pass on a machine that never
//! executed an instruction — the exact failure mode the whole campaign
//! exists to remove. Power-on screen RAM holds glyph 0, which is blank, so
//! the display can only light if the fill ran.
//!
//! The images are generated by
//! `test-data/synthetic-firmware/build-synthetic-firmware.py`.

use std::path::PathBuf;

use machine_commodore_pet::Pet;

/// The PET's phosphor green.
const LIT: u32 = 0xFF00_FF00;

fn firmware(name: &str) -> Vec<u8> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../test-data/synthetic-firmware")
        .join(name);
    std::fs::read(path).expect("firmware image")
}

fn booted(kernal: &str) -> Pet {
    let mut machine = Pet::new(
        firmware(kernal),
        firmware("commodore-pet-basic.rom"),
        firmware("commodore-pet-editor.rom"),
        firmware("commodore-pet-chargen.rom"),
        40,
    );
    for _ in 0..20 {
        machine.run_frame();
    }
    machine
}

#[test]
fn synthetic_firmware_fills_the_screen_with_a_solid_glyph() {
    let machine = booted("commodore-pet-kernal.rom");
    let lit = machine
        .framebuffer()
        .iter()
        .filter(|&&pixel| pixel == LIT)
        .count();
    // 64,000 in practice — 320x200, exactly the 40x25 display area. The rest
    // is border, which writing screen RAM cannot reach.
    assert!(
        lit > machine.framebuffer().len() / 2,
        "the solid glyph should light the display area; got {lit} of {} pixels",
        machine.framebuffer().len()
    );
}

/// The control image spins without filling screen RAM. Screen RAM still
/// holds glyph 0, which the same character ROM defines as blank — so a
/// machine that ran nothing shows nothing, even though the solid glyph is
/// sitting in the character ROM the whole time.
#[test]
fn the_control_image_lights_nothing() {
    let machine = booted("commodore-pet-kernal-control.rom");
    assert_eq!(
        machine.framebuffer().iter().filter(|&&p| p == LIT).count(),
        0,
        "a machine that ran no firmware must leave the screen dark"
    );
}
