//! Fixture-free proof that the machine starts.
//!
//! The Ace needs its manufacturer's ROM to reach a prompt, and that ROM
//! cannot be copied to a public runner. So this asks the weaker question CI
//! *can* answer: put code this project wrote in the ROM socket, and see
//! whether the machine runs it.
//!
//! A pass proves the CPU executed from reset, the ROM is readable where the
//! memory map says it is, character RAM took its writes, the video hardware
//! fetched them, and a frame reached the framebuffer. It does **not** prove
//! the real firmware boots.
//!
//! The Ace is the cheapest of these to flood, because its character set is
//! **RAM** rather than ROM. Video RAM already holds glyph 0 everywhere at
//! power-on, so redefining glyph 0 as eight solid bytes fills the screen in
//! eight stores — no loop over the display at all.
//!
//! It is also monochrome, so the flood is ink rather than a colour.
//!
//! The image is generated by
//! `test-data/synthetic-firmware/build-synthetic-firmware.py`.

use std::path::PathBuf;

use machine_jupiter_ace::JupiterAce;

/// Ink. The control renders none of it — a blank screen is all paper.
const INK: u32 = 0xFF00_0000;

fn firmware(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../test-data/synthetic-firmware")
        .join(name)
}

fn booted(name: &str) -> JupiterAce {
    let rom = std::fs::read(firmware(name)).expect("firmware image");
    let mut machine = JupiterAce::new(rom, 16 * 1024).expect("synthetic ROM should init");
    for _ in 0..10 {
        machine.run_frame();
    }
    machine
}

#[test]
fn synthetic_firmware_runs_and_fills_the_display() {
    let machine = booted("jupiter-ace.rom");
    let ink = machine
        .framebuffer()
        .iter()
        .filter(|&&pixel| pixel == INK)
        .count();
    // The display area is 64% of the buffer; the rest is border, which a
    // redefined glyph cannot reach.
    assert!(
        ink > machine.framebuffer().len() / 2,
        "a solid glyph 0 should fill the display area with ink; got {ink} of {} pixels",
        machine.framebuffer().len()
    );
}

/// The control image spins without redefining the glyph.
#[test]
fn the_control_image_renders_no_ink_at_all() {
    let machine = booted("jupiter-ace-control.rom");
    assert_eq!(
        machine.framebuffer().iter().filter(|&&p| p == INK).count(),
        0,
        "a machine that ran no firmware must show an entirely blank screen"
    );
}
