[package]
name = "emu198x-spectrum"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
common-sinclair-zx-spectrum = { path = "../common-sinclair-zx-spectrum" }
emu198x-native-video = { path = "../emu198x-native-video" }
emu198x-shell = { path = "../emu198x-shell" }
muda.workspace = true
runtime-sinclair-zx-spectrum = { path = "../runtime-sinclair-zx-spectrum" }
thiserror.workspace = true
winit.workspace = true

[lints]
workspace = true
