[package]
name = "format-nintendo-game-boy-cartridge"
description = "Game Boy cartridge header parser + Cartridge construction"
edition.workspace = true
version = "0.2.0"
license.workspace = true
repository.workspace = true

[dependencies]
nintendo-game-boy-mbc = { path = "../nintendo-game-boy-mbc", version = "0.2.0" }
serde = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
