[package]
name = "format-nintendo-game-boy-cartridge"
description = "Game Boy cartridge header parser + Cartridge construction"
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
nintendo-game-boy-mbc = { path = "../nintendo-game-boy-mbc", version = "0.19.0" }
serde = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
