[package]
name = "runtime-sinclair-zx80"
description = "Sinclair ZX80 family metadata and headless runtime wrapper"
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
format-sinclair-zx80-o = { path = "../format-sinclair-zx80-o", version = "0.18.0" }
emu198x-shell = { path = "../emu198x-shell", version = "0.18.0" }
machine-sinclair-zx80 = { path = "../machine-sinclair-zx80", version = "0.18.0" }
emu198x-zilog-z80 = { path = "../emu198x-zilog-z80", version = "0.6.0" }
postcard = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
