//! Fixture-free proof that the machine starts.
//!
//! The Memotech MTX needs its manufacturer's ROM to reach a prompt, and
//! that ROM cannot be copied to a public runner. So this asks the weaker
//! question CI *can* answer: put code this project wrote in the ROM
//! socket, and see whether the machine runs it.
//!
//! A pass proves the reset vector was fetched, the ROM is readable where
//! the memory map says it is, the CPU executed, the TMS9918 took its
//! register writes, and a frame reached the framebuffer. It does **not**
//! prove the real firmware boots — that claim belongs to the Sinclair and
//! Amstrad line, whose ROMs may be distributed.
//!
//! The image is generated by
//! `test-data/synthetic-firmware/build-synthetic-firmware.py`.

use std::path::PathBuf;

use machine_memotech_mtx::{Mtx, MtxModel};

/// TMS9918 palette entry 15. The power-on backdrop is entry 0, which is
/// transparent, so white cannot appear unless the firmware ran.
const WHITE: u32 = 0xFFFF_FFFF;

fn firmware() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../test-data/synthetic-firmware/memotech-mtx.rom")
}

fn booted(rom: Vec<u8>) -> Mtx {
    let mut machine = Mtx::new(rom, MtxModel::Mtx512).expect("synthetic firmware should load");
    for _ in 0..5 {
        machine.run_frame();
    }
    machine
}

fn uniform(machine: &Mtx) -> Option<u32> {
    let first = *machine.framebuffer().first()?;
    machine
        .framebuffer()
        .iter()
        .all(|&pixel| pixel == first)
        .then_some(first)
}

#[test]
fn the_mtx_runs_firmware_and_paints_its_backdrop() {
    let rom = std::fs::read(firmware())
        .unwrap_or_else(|err| panic!("synthetic firmware should be committed: {err}"));
    assert_eq!(uniform(&booted(rom)), Some(WHITE));
}

/// The check is only worth having if it can fail.
#[test]
fn firmware_that_programs_nothing_does_not_look_like_a_boot() {
    let mut rom = std::fs::read(firmware()).expect("firmware should be committed");
    // Spin at the reset vector, before any VDP register is written.
    rom[0] = 0x18;
    rom[1] = 0xFE;
    assert_ne!(uniform(&booted(rom)), Some(WHITE));
}
