[package]
name = "format-atari-8bit-atr"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
emu198x-test-skip = { path = "../emu198x-test-skip", version = "0.20.0" }

[lints]
workspace = true
