[package]
name = "sinclair-ula-7k010e"
description = "Sinclair 7K010E ULA — the 128K and +2 ZX Spectrum's custom chip"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
common-sinclair-zx-spectrum = { path = "../common-sinclair-zx-spectrum" }
