//! Fixture-free proof that the machine starts.
//!
//! The CPC needs its manufacturer's ROM to reach a prompt, and that ROM
//! cannot be copied to a public runner. So this asks the weaker question CI
//! *can* answer: put code this project wrote in the ROM socket, and see
//! whether the machine runs it.
//!
//! It does **not** prove the real firmware boots.
//!
//! Unlike every other synthetic-firmware machine here, **there is no display
//! at all until the firmware makes one.** The 6845's registers are zero at
//! reset, so the program has to build a raster before it can colour it. That
//! makes this the strongest of the synthetic proofs: a pass means the CPU
//! executed roughly forty instructions of setup in the right order, the
//! CRTC took every register write, the Gate Array took its pen and border writes, and a frame came out.
//!
//! The image is generated by
//! `test-data/synthetic-firmware/build-synthetic-firmware.py`.

use std::path::PathBuf;

use machine_amstrad_cpc::AmstradCpc;

/// What pen 0 and the border set to hardware colour 6 render. The control
/// image renders black — with no CRTC programming there is no raster.
const PEN: u32 = 0xFF00_6060;

fn firmware(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../test-data/synthetic-firmware")
        .join(name)
}

fn booted(name: &str) -> AmstradCpc {
    let rom = std::fs::read(firmware(name)).expect("firmware image");
    let mut machine = AmstradCpc::new(&rom).expect("synthetic firmware should init");
    for _ in 0..20 {
        machine.run_frame();
    }
    machine
}

#[test]
fn synthetic_firmware_builds_a_raster_and_floods_it() {
    let machine = booted("amstrad-cpc.rom");
    assert!(
        machine.framebuffer().iter().all(|&pixel| pixel == PEN),
        "a zeroed screen under pen 0 should make the whole frame one colour"
    );
}

/// The control image spins without programming the CRTC. There is no
/// display to colour, so the frame stays black.
#[test]
fn the_control_image_renders_no_raster() {
    let machine = booted("amstrad-cpc-control.rom");
    assert_eq!(
        machine.framebuffer().iter().filter(|&&p| p == PEN).count(),
        0,
        "a machine that never programmed its CRTC cannot show a raster"
    );
}
