[package]
name = "atari-antic"
description = "Atari ANTIC display list processor — Atari 5200, 800XL, 130XE"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
atari-gtia = { path = "../atari-gtia", version = "0.19.0" }
serde = { workspace = true }
serde-big-array = { workspace = true }

[lints]
workspace = true
