//! Fixture-free proof that the machine starts.
//!
//! The VIC-20 needs its manufacturer's ROM to reach a prompt, and that ROM
//! cannot be copied to a public runner. So this asks the weaker question CI
//! *can* answer: put code this project wrote in the ROM socket, and see
//! whether the machine runs it.
//!
//! A pass proves the reset vector was fetched, the ROM is readable where the
//! memory map says it is, the CPU executed, the VIC took its register write,
//! and a frame reached the framebuffer. It does **not** prove the real
//! firmware boots — that claim belongs to the machines whose own ROMs may be
//! distributed, or which have a free reimplementation.
//!
//! The image is generated by
//! `test-data/synthetic-firmware/build-synthetic-firmware.py`, which also
//! builds a control image that spins without touching the hardware. Every
//! control renders black, which is where the expected colour below comes
//! from — measured against "never ran", not assumed.

use std::path::PathBuf;

use machine_commodore_vic_20::{Vic20, Vic20Model};

/// What `$900F = $2A` renders: screen colour 2 and border colour 2. The
/// power-on framebuffer is black, so this cannot appear unless the firmware
/// ran.
const RED: u32 = 0xFF78_2922;

fn firmware(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../test-data/synthetic-firmware")
        .join(name)
}

#[test]
fn synthetic_firmware_runs_and_floods_the_display() {
    let kernal = std::fs::read(firmware("commodore-vic-20-kernal.rom")).expect("kernal image");
    let basic = std::fs::read(firmware("commodore-vic-20-basic.rom")).expect("basic image");
    let chargen = std::fs::read(firmware("commodore-vic-20-chargen.rom")).expect("chargen image");

    let mut machine = Vic20::new(kernal, basic, chargen, Vic20Model::Pal, 0);
    for _ in 0..10 {
        machine.run_frame();
    }

    let framebuffer = machine.framebuffer();
    let red = framebuffer.iter().filter(|&&pixel| pixel == RED).count();

    // The whole window, border included: $2A is screen colour 2 and border
    // colour 2, so nothing on screen should be any other colour.
    //
    // This was a fraction of the buffer for as long as the border was painted
    // by a frame-start fill guarded on `scanline == 0 && pixel_x == 0` — a
    // pair that never occurred, because the tick which wraps the frame returns
    // early. The border stayed the power-on black and the test could only ask
    // about the 176x184 the display covers, which is 49% of a PAL window.
    // Compositing the border with the picture fixed it (#1087).
    assert_eq!(
        red,
        framebuffer.len(),
        "the VIC should flood its whole window with $900F's colour; got {red} of {} pixels",
        framebuffer.len()
    );
}

/// The control image spins without touching the VIC. If this ever renders
/// red, the colour is coming from somewhere other than the firmware and the
/// test above proves nothing.
#[test]
fn the_control_image_renders_no_red_at_all() {
    let kernal =
        std::fs::read(firmware("commodore-vic-20-kernal-control.rom")).expect("control image");
    let basic = std::fs::read(firmware("commodore-vic-20-basic.rom")).expect("basic image");
    let chargen = std::fs::read(firmware("commodore-vic-20-chargen.rom")).expect("chargen image");

    let mut machine = Vic20::new(kernal, basic, chargen, Vic20Model::Pal, 0);
    for _ in 0..10 {
        machine.run_frame();
    }

    assert_eq!(
        machine.framebuffer().iter().filter(|&&p| p == RED).count(),
        0,
        "a machine that ran no firmware must not show the firmware's colour"
    );
}
