[package]
name = "format-sinclair-zx-spectrum-rzx"
description = "RZX input recording format parser and writer for ZX Spectrum replay testing"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
flate2 = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
