//! Sinclair ZX81 (1981) — Z80A + 8 KB ROM + ULA with NMI-driven display.
//!
//! Fresh-write against the workspace pin-driven bus pattern (RULES.md
//! rule 6). Donor at `Emu198x-Oldest/crates/machine-sinclair-zx81/`
//! used the deprecated `emu_core::Bus` callback; this file uses it as
//! the system spec but wires [`emu198x_zilog_z80::Z80`] through its public pin
//! fields and `bus_request()` collapse. The keyboard matrix is shared
//! with the ZX80 — see [`sinclair_zx81_ula`]; the display is not, and
//! [`video`] says why.
//!
//! # The ZX81
//!
//! Sinclair's £49.95 follow-up to the ZX80 (1981). Around 1.5 million
//! units sold worldwide. The display is generated by the processor:
//! the ULA raises NMI once a scan line, the ROM's handler executes a
//! `HALT`, and the CPU then runs *through the display file* while the
//! ULA forces each byte to a `NOP` and shifts the character it names
//! out to the screen. There is no video RAM and no frame buffer. See
//! [`video`] for the mechanism and what settles each part of it.
//!
//! - **CPU:** Zilog Z80A at 3.25 MHz
//! - **ROM:** 8 KB at `$0000-$1FFF` (mirrored to `$2000-$3FFF` and
//!   `$8000-$BFFF`)
//! - **RAM:** 1 KB at `$4000-$43FF` (or 16 KB with the RAM pack);
//!   mirrored to `$C000-$FFFF`
//! - **Display:** 32 × 24 characters, generated by the CPU executing
//!   the display file with the ULA reading the bus
//! - **Audio:** none
//! - **Keyboard:** identical 8 × 5 matrix to the Spectrum / ZX80
//!
//! # NMI generator control
//!
//! Per the donor: OUT to an even port (e.g. `$FE`) enables the NMI
//! generator; OUT to a port with bit 1 clear (e.g. `$FD`) disables it.
//! ROM uses OUT($FD)/OUT($FE).

pub mod input;
mod keyboard;
pub mod video;

pub use input::Zx81Key;
pub use keyboard::KeyboardState;
pub use video::{FB_WIDTH, Zx81Video};

/// Samples a second the host is fed. Matches the runtime's `AUDIO_SAMPLE_RATE`.
const AUDIO_SAMPLE_RATE: u32 = 48_000;
/// T-states a second, which is what `master_clock` counts.
const CPU_CLOCK_HZ: u64 = 3_250_000;

use emu198x_zilog_z80::z80::{BusOp, Z80};
use serde::{Deserialize, Serialize};

/// The EAR level the port reports with nothing plugged in.
const fn ear_idle() -> bool {
    true
}

/// Which television standard the board is strapped for.
///
/// The strap reads back on **bit 6** of the keyboard port. The ROM checks it
/// after scanning the keys and sets `MARGIN` ($4028) from it: high gives
/// `$37` (55), the 50 Hz frame margin; low gives `$1F` (31) for 60 Hz. That
/// one strap is the whole of the difference as far as the ROM is concerned,
/// and grounding it is what the American board does.
///
/// Named for the strap rather than PAL/NTSC because the ZX81 has no colour
/// system to differ about -- only the frame rate changes.
///
/// # On the bit number
///
/// *The Ins and Outs of the TS1000 & ZX81* (Thomasson, p42) puts this on bit
/// 5 and calls bit 6 a "tape data available" flag. The shipped ROM disagrees:
/// driving each of bits 5, 6 and 7 independently across all eight
/// combinations moves `MARGIN` with **bit 6 alone**, and bits 5 and 7 have no
/// effect on it. The ROM is Sinclair's own and decides what it reads, so it
/// is taken as the authority here. See `zx81_margin_follows_bit_6` and
/// `reference/by-system/sinclair-zx81/verification.md`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TelevisionStandard {
    /// Strap high -- 50 Hz. The British board.
    #[default]
    FiftyHz,
    /// Strap grounded -- 60 Hz. The American board.
    SixtyHz,
}

impl TelevisionStandard {
    /// Frame budget for a host that advances the machine in whole frames.
    ///
    /// The ZX81 has no frame counter. The picture is generated by the ROM, so
    /// the frame length is whatever the ROM makes it, and a host budget must
    /// sit **at or below the shortest frame the machine will emit** -- one
    /// longer leaves the clock short of its target after a frame and the host
    /// runs a second, which is the machine at double speed.
    ///
    /// `207 x 312` (64,584) is the wrong figure for this. It is the field
    /// *backstop*, the length a field runs to when no software sync ends it
    /// first, so it is the longest frame rather than the shortest. Measured
    /// against the stock ROM over 400 frames:
    ///
    /// | Strap | Settled frame | Startup backstop | Rate |
    /// |---|---|---|---|
    /// | 50 Hz | **64,166** | 64,584 | 50.65 Hz |
    /// | 60 Hz | **54,230** | 64,584 | 59.93 Hz |
    ///
    /// **Re-measured for #302, and by three T-states each.** The previous
    /// pair, 64,163 and 54,227, were taken from a machine that could not
    /// reach SLOW: the ROM's capability probe never saw an NMI, so it
    /// concluded it was running on a ZX80 and stayed in FAST. These figures
    /// are the same measurement with `CDFLAG` reading `$C0`, which is what a
    /// ZX81 powers on into. The rates are unchanged to two decimals, which is
    /// the check that they are the same quantity rather than a new one.
    ///
    /// The two settled minima are the budgets. Note the 60 Hz one is far below
    /// the 50 Hz one, which is why this cannot be a single shared constant.
    ///
    /// The larger pair in each row is the backstop, seen while the ROM is
    /// still starting up and has not established its sync.
    ///
    /// # Scope
    ///
    /// These are the stock ROM in SLOW mode and nothing wider.
    /// `MIN_FRAME_T` (52,000) is the only real guarantee, so a program driving
    /// its own sync near it would still double-step. A per-variant budget
    /// cannot express a frame length that varies per program; that is a limit
    /// of the pacing contract rather than of these figures.
    #[must_use]
    pub const fn slow_mode_frame_tstates(self) -> u32 {
        match self {
            Self::FiftyHz => 64_166,
            Self::SixtyHz => 54_230,
        }
    }
}

/// Sinclair ZX81 machine.
#[derive(Serialize, Deserialize)]
pub struct Zx81 {
    cpu: Z80,
    rom: Vec<u8>,
    ram: Vec<u8>,
    ram_mask: u16,
    video: Zx81Video,
    /// An NMI edge that arrived while the ULA had the processor's clock.
    #[serde(default)]
    nmi_pending: bool,
    #[serde(default)]
    nmi_line_prev: bool,
    keyboard: KeyboardState,
    master_clock: u64,
    frame_count: u64,
    /// `/REFRESH` last T-state, so its rising edge can be seen.
    prev_rfsh: bool,
    /// Board strap, read back on port bit 6.
    #[serde(default)]
    television_standard: TelevisionStandard,
    /// Cassette EAR level with no tape threaded, read back on port bit 7.
    /// Its idle level is unverified, so it keeps the value the port has
    /// always returned.
    #[serde(default = "ear_idle")]
    ear_input: bool,
    /// Absolute master-clock times at which the cassette line transitions.
    /// Even index means the line goes one way, odd the other, so the level is
    /// simply the parity of how many have passed.
    #[serde(default)]
    tape_in: Vec<u64>,
    /// How far through `tape_in` playback has got.
    #[serde(default)]
    tape_pos: usize,
    /// When recording, the times at which the ROM touched a port. The ZX81
    /// has no cassette data register -- the bus access *is* the signal.
    #[serde(default)]
    tape_out: Option<Vec<u64>>,
    /// When `Some`, every I/O port access is appended here (debug trace).
    #[serde(skip)]
    io_trace: Option<Vec<IoEvent>>,
    /// Host-facing, and drained every frame; see `take_audio_buffer`.
    #[serde(default, skip)]
    audio_buffer: Vec<f32>,
    #[serde(default)]
    audio_accum: u64,
}

impl Zx81 {
    /// Create a new ZX81. `rom` must be 8 KB. `ram_size` is 1024
    /// (unexpanded) or 16384 (16 KB RAM pack).
    pub fn new(rom: Vec<u8>, ram_size: usize) -> Result<Self, String> {
        if rom.len() != 0x2000 {
            return Err(format!("ZX81 ROM must be 8192 bytes, got {}", rom.len()));
        }
        if !ram_size.is_power_of_two() || ram_size > 0x4000 {
            return Err(format!(
                "ZX81 RAM size must be a power of two <= 16384, got {ram_size}"
            ));
        }
        Ok(Self {
            cpu: Z80::new(),
            rom,
            ram: vec![0; ram_size],
            ram_mask: (ram_size - 1) as u16,
            video: Zx81Video::new(TelevisionStandard::default()),
            nmi_pending: false,
            nmi_line_prev: false,
            keyboard: KeyboardState::new(),
            master_clock: 0,
            frame_count: 0,
            prev_rfsh: false,
            television_standard: TelevisionStandard::default(),
            ear_input: ear_idle(),
            tape_in: Vec::new(),
            tape_pos: 0,
            tape_out: None,
            io_trace: None,
            audio_buffer: Vec::with_capacity(1024),
            audio_accum: 0,
        })
    }

    /// Assemble a read of the keyboard port.
    ///
    /// | Bit | Source |
    /// |---|---|
    /// | 0-4 | Keyboard half-row, active low |
    /// | 5 | Not driven -- reads high |
    /// | 6 | Television-standard strap |
    /// | 7 | Cassette EAR level |
    ///
    /// Bits 6 and 7 used to be forced high with bit 5, so the machine could
    /// not report its own strap: every ZX81 was a 50 Hz one whatever profile
    /// it claimed.
    fn read_keyboard_port(&mut self, addr_high: u8) -> u8 {
        let mut value = self.keyboard.read(addr_high) & 0x1F | 0x20;
        if self.television_standard == TelevisionStandard::FiftyHz {
            value |= 0x40;
        }
        if self.ear_level() {
            value |= 0x80;
        }
        value
    }

    /// The cassette line's level now. A threaded tape drives it; otherwise it
    /// sits at whatever `set_ear_input` last said.
    fn ear_level(&mut self) -> bool {
        if self.tape_in.is_empty() {
            return self.ear_input;
        }
        while self
            .tape_in
            .get(self.tape_pos)
            .is_some_and(|&edge| edge <= self.master_clock)
        {
            self.tape_pos += 1;
        }
        self.tape_pos % 2 == 1
    }

    /// Notes a bus access while recording. `SAVE` emits each pulse as an
    /// `OUT` followed by an `IN`, so the times of those accesses are the
    /// waveform.
    fn record_tape_edge(&mut self) {
        if let Some(out) = &mut self.tape_out {
            out.push(self.master_clock);
        }
    }

    /// One audio sample per 48 kHz period, taken from the pin that carries
    /// both video and cassette output.
    fn tick_audio(&mut self) {
        self.audio_accum += u64::from(AUDIO_SAMPLE_RATE);
        if self.audio_accum >= CPU_CLOCK_HZ {
            self.audio_accum -= CPU_CLOCK_HZ;
            self.audio_buffer
                .push(if self.video.output_level() { 0.5 } else { -0.5 });
        }
    }

    /// Takes the samples generated since the last call.
    pub fn take_audio_buffer(&mut self) -> Vec<f32> {
        std::mem::take(&mut self.audio_buffer)
    }

    /// Threads a tape. `edges` are transition times relative to now.
    ///
    /// **Leave a lead-in.** A tape whose first transition is at zero arrives
    /// while the ROM is still settling and it reads nothing at all -- it stays
    /// in its `LOAD` loop for the whole tape and accepts zero bytes, which
    /// looks like a corrupt image rather than a mistimed one.
    /// `Zx81Image::to_pulses` starts its first pulse 1,500,000 master clocks
    /// in, a little under half a second, and replaying a recorded `SAVE`
    /// wants the same. Rebasing a recording so that it starts at zero is the
    /// obvious thing to do and the thing that breaks it; `tape_save.rs` has
    /// the measurement.
    pub fn insert_tape(&mut self, edges: &[u64]) {
        let start = self.master_clock;
        self.tape_in = edges.iter().map(|e| start.saturating_add(*e)).collect();
        self.tape_pos = 0;
    }

    /// Lifts the tape off.
    pub fn eject_tape(&mut self) {
        self.tape_in.clear();
        self.tape_pos = 0;
    }

    /// Edges left to play.
    #[must_use]
    pub fn tape_remaining(&self) -> usize {
        self.tape_in.len().saturating_sub(self.tape_pos)
    }

    /// Starts recording the cassette output.
    pub fn start_tape_recording(&mut self) {
        self.tape_out = Some(Vec::new());
    }

    /// Stops recording and returns the edge times, in master clocks.
    pub fn take_tape_recording(&mut self) -> Vec<u64> {
        self.tape_out.take().unwrap_or_default()
    }

    /// The board's television-standard strap.
    #[must_use]
    pub fn television_standard(&self) -> TelevisionStandard {
        self.television_standard
    }

    /// Strap the board for 50 Hz or 60 Hz. The ROM reads this on its next
    /// keyboard scan and sets `MARGIN` from it.
    pub fn set_television_standard(&mut self, standard: TelevisionStandard) {
        self.television_standard = standard;
        // The two regions do not show the same number of lines, so the window
        // is a different size and the buffer has to follow (#1119).
        self.video.set_standard(standard);
    }

    /// Framebuffer row the text area starts on, which the region decides.
    #[must_use]
    pub fn text_top(&self) -> u32 {
        self.video.text_top()
    }

    /// The cassette EAR level the port reports.
    #[must_use]
    pub fn ear_input(&self) -> bool {
        self.ear_input
    }

    /// Drive the cassette EAR input, which the ROM polls on bit 7 during
    /// `LOAD`.
    pub fn set_ear_input(&mut self, level: bool) {
        self.ear_input = level;
    }

    pub fn run_frame(&mut self) -> u64 {
        let start = self.master_clock;
        self.video.clear();
        loop {
            self.tick_tstate();
            if self.video.take_frame_complete() {
                break;
            }
        }
        self.frame_count += 1;
        self.master_clock - start
    }

    fn tick_tstate(&mut self) {
        self.master_clock += 1;
        self.video.tick();
        self.tick_audio();

        // Two CPU half-cycles per T-state. `Z80::tick` advances one
        // half-cycle — `T1Rise` then `T1Fall` — so calling it once per
        // T-state ran the CPU at half speed: a `NOP` cost 8 T-states against
        // the Z80's 4.
        // The NMI pin is presented whether or not the clock is gated.
        //
        // TR1 conducts when HALT is false and NMI is true (reference §1), so
        // the processor is suspended for exactly the pulse that would have
        // interrupted it. Gating the clock does not disconnect the pin: the
        // Z80 latches the edge asynchronously and services it when the clock
        // returns. Sampling the pin only on the ticks the ULA allows meant a
        // running processor never saw one, so the ROM's SLOW probe at `$0207`
        // always failed and the machine could not leave FAST. See #302.
        let nmi_line = self.video.nmi_line();
        if nmi_line && !self.nmi_line_prev {
            self.nmi_pending = true;
        }
        self.nmi_line_prev = nmi_line;

        // The ULA takes the processor's clock away across the line sync, which
        // is what holds every line's characters at the same T-states. A
        // halted CPU is already waiting for the interrupt, so it is not held.
        if self.video.holds_cpu() && !self.cpu.halt {
            return;
        }

        for _ in 0..2 {
            // The generator's pulse, sampled before the tick because the Z80
            // samples its interrupt inputs during its own. A pulse that began
            // while the clock was gated is presented here instead, once, which
            // is enough for the processor's own latch to take it.
            self.cpu.nmi = nmi_line || self.nmi_pending;

            self.cpu.tick();
            self.handle_bus();

            let rfsh = self.cpu.rfsh;
            if rfsh {
                // INT is wired to address line A6 (reference §1), so an
                // interrupt is generated whenever the address on the bus has
                // A6 low. The refresh address is `I:R` and `R` counts up as
                // the display is fetched, so the interrupt arrives once per
                // display line and the ROM's `$0038` handler moves to the
                // next one.
                self.cpu.irq = self.cpu.addr & 0x0040 == 0;
            }
            if rfsh && !self.prev_rfsh {
                let rom = &self.rom;
                let ram = &self.ram;
                let mask = self.ram_mask;
                self.video.refresh(self.cpu.addr, |addr| match addr {
                    0x0000..=0x3FFF => rom[(addr & 0x1FFF) as usize],
                    0x4000..=0x7FFF => ram[((addr - 0x4000) & mask) as usize],
                    0x8000..=0xBFFF => rom[(addr & 0x1FFF) as usize],
                    0xC000..=0xFFFF => ram[((addr - 0xC000) & mask) as usize],
                });
            }
            self.prev_rfsh = rfsh;
        }

        // The processor has now ticked with the pin presented, so its own
        // latch holds the edge and this one has done its job.
        self.nmi_pending = false;
    }

    fn handle_bus(&mut self) {
        match self.cpu.bus_request() {
            Some(BusOp::MemRead) => {
                let byte = self.mem_read(self.cpu.addr);
                // A display fetch is answered with `$00` on the CPU side
                // while the real byte goes to the character latch. One read,
                // two results — which is the whole trick.
                //
                // The latch is inhibited while `/HALT` is low. A `HALT` ends
                // the display line, but the Z80 goes on issuing M1 cycles
                // until the interrupt arrives, with the address bus holding
                // the byte after it — display file, A15 set, and as often as
                // not a character code.
                self.cpu.data_in = if self.cpu.m1 && !self.cpu.halt {
                    self.video.opcode_fetch(self.cpu.addr, byte).unwrap_or(byte)
                } else {
                    byte
                };
            }
            Some(BusOp::MemWrite) => {
                self.mem_write(self.cpu.addr, self.cpu.data);
            }
            Some(BusOp::IoRead) => {
                let io_port = self.cpu.addr;
                let io_pc = self.cpu.regs.pc;
                let io_val = self.io_read(self.cpu.addr);
                self.cpu.data_in = io_val;
                if let Some(trace) = &mut self.io_trace {
                    trace.push(IoEvent {
                        pc: io_pc,
                        port: io_port,
                        value: io_val,
                        write: false,
                    });
                }
            }
            Some(BusOp::IoWrite) => {
                if let Some(trace) = &mut self.io_trace {
                    trace.push(IoEvent {
                        pc: self.cpu.regs.pc,
                        port: self.cpu.addr,
                        value: self.cpu.data,
                        write: true,
                    });
                }
                self.io_write(self.cpu.addr, self.cpu.data);
            }
            Some(BusOp::IntAck) => {
                self.cpu.data_in = 0xFF;
            }
            None => {}
        }
    }

    fn mem_read(&self, addr: u16) -> u8 {
        match addr {
            0x0000..=0x3FFF | 0x8000..=0xBFFF => self.rom[(addr & 0x1FFF) as usize],
            0x4000..=0x7FFF => self.ram[((addr - 0x4000) & self.ram_mask) as usize],
            0xC000..=0xFFFF => self.ram[((addr - 0xC000) & self.ram_mask) as usize],
        }
    }

    fn mem_write(&mut self, addr: u16, value: u8) {
        match addr {
            0x0000..=0x3FFF | 0x8000..=0xBFFF => {}
            0x4000..=0x7FFF => {
                self.ram[((addr - 0x4000) & self.ram_mask) as usize] = value;
            }
            0xC000..=0xFFFF => {
                self.ram[((addr - 0xC000) & self.ram_mask) as usize] = value;
            }
        }
    }

    fn io_read(&mut self, port: u16) -> u8 {
        // Reading the bus is also how the ROM drives the cassette output one
        // way: `SAVE` emits each pulse as an `OUT` followed by an `IN`.
        self.record_tape_edge();
        if port & 0x01 == 0 {
            // The same read that scans the keyboard starts the vertical sync:
            // one port, two jobs, which is why the ROM's vertical interval is
            // a keyboard read it does not care about the answer to.
            self.video.vsync_start();
            return self.read_keyboard_port((port >> 8) as u8);
        }
        0xFF
    }

    fn io_write(&mut self, port: u16, _value: u8) {
        self.record_tape_edge();
        // OUT to even port enables NMI generator; OUT with bit 1 clear
        // disables it. SLOW and FAST: with the generator off there is no line
        // clock, so the ROM never enters the display routine and the picture
        // goes — which is what FAST mode is.
        // Any OUT releases the vertical sync, and the frame ends there.
        self.video.vsync_stop();
        if port & 0x01 == 0 {
            self.video.set_nmi_enabled(true);
        }
        if port & 0x02 == 0 {
            self.video.set_nmi_enabled(false);
        }
    }

    #[must_use]
    pub fn framebuffer(&self) -> &[u32] {
        self.video.framebuffer()
    }

    #[must_use]
    pub fn framebuffer_width(&self) -> u32 {
        self.video.framebuffer_width()
    }

    #[must_use]
    pub fn framebuffer_height(&self) -> u32 {
        self.video.framebuffer_height()
    }

    pub fn press_key(&mut self, key: Zx81Key) {
        let (row, bit) = key.matrix();
        self.keyboard.set_key(row, bit, true);
    }

    pub fn release_key(&mut self, key: Zx81Key) {
        let (row, bit) = key.matrix();
        self.keyboard.set_key(row, bit, false);
    }

    pub fn release_all_keys(&mut self) {
        self.keyboard.release_all();
    }

    #[must_use]
    pub fn peek_memory(&self, addr: u16) -> u8 {
        self.mem_read(addr)
    }

    #[must_use]
    pub fn nmi_enabled(&self) -> bool {
        self.video.nmi_enabled()
    }

    #[must_use]
    pub fn cpu(&self) -> &Z80 {
        &self.cpu
    }

    pub fn cpu_mut(&mut self) -> &mut Z80 {
        &mut self.cpu
    }

    #[must_use]
    pub fn master_clock(&self) -> u64 {
        self.master_clock
    }

    #[must_use]
    pub fn frame_count(&self) -> u64 {
        self.frame_count
    }
}

impl emu198x_zilog_z80::Z80Stepper for Zx81 {
    fn z80_instructions_retired(&self) -> u64 {
        self.cpu.instructions_retired()
    }

    fn step_tick(&mut self) {
        self.tick_tstate();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn trap_rom() -> Vec<u8> {
        let mut rom = vec![0u8; 0x2000];
        rom[0] = 0xF3;
        rom[1] = 0x76;
        rom
    }

    #[test]
    fn frame_advances_master_clock_and_count() {
        let mut sys = Zx81::new(trap_rom(), 1024).expect("init");
        let clocks = sys.run_frame();
        assert!(clocks > 0);
        assert_eq!(sys.frame_count(), 1);
    }

    #[test]
    fn rom_size_validated() {
        assert!(Zx81::new(vec![0u8; 4096], 1024).is_err());
    }

    #[test]
    fn ram_mirrors_at_c000() {
        let mut sys = Zx81::new(trap_rom(), 1024).expect("init");
        sys.mem_write(0x4000, 0x42);
        assert_eq!(sys.mem_read(0xC000), 0x42);
    }

    #[test]
    fn nmi_enabled_toggles_via_io() {
        let mut sys = Zx81::new(trap_rom(), 1024).expect("init");
        assert!(!sys.nmi_enabled());
        sys.io_write(0x00FE, 0);
        assert!(sys.nmi_enabled());
        sys.io_write(0x00FD, 0);
        assert!(!sys.nmi_enabled());
    }

    #[test]
    fn keyboard_press_release() {
        let mut sys = Zx81::new(trap_rom(), 1024).expect("init");
        sys.press_key(Zx81Key::A);
        assert_eq!(sys.io_read(0xFDFE) & 0x01, 0x00);
        sys.release_key(Zx81Key::A);
        assert_eq!(sys.io_read(0xFDFE) & 0x01, 0x01);
    }

    #[test]
    fn snapshot_round_trips_live_state() {
        let mut sys = Zx81::new(trap_rom(), 1024).expect("init");
        sys.run_frame();

        // Write a RAM byte so the captured state is non-trivial. RAM is at
        // $4000+ on the ZX81; confirm the write landed via the read path.
        sys.poke(0x4000, 0x5A);
        assert_eq!(sys.peek(0x4000), 0x5A);

        let first = postcard::to_allocvec(&sys).expect("encode first");

        // Advance and re-serialise — the master clock / frame count move on,
        // so the two snapshots must differ.
        sys.run_frame();
        let second = postcard::to_allocvec(&sys).expect("encode second");
        assert_ne!(first, second, "advancing a frame must change the snapshot");

        // Restoring the first snapshot and re-encoding must be byte-identical.
        let restored: Zx81 = postcard::from_bytes(&first).expect("decode first");
        let reencoded = postcard::to_allocvec(&restored).expect("re-encode restored");
        assert_eq!(first, reencoded, "round-trip must be byte-identical");
    }

    /// The non-keyboard half of the port, bit by bit.
    ///
    /// Bit 5 is not driven and reads high. Bit 6 is the strap and bit 7 the
    /// EAR line — which bit is which was settled against the shipped ROM, see
    /// `zx81_margin_follows_bit_6` in `tests/rom_boot.rs`.
    #[test]
    fn the_port_upper_bits_carry_the_strap_and_the_ear_line() {
        let mut machine = Zx81::new(trap_rom(), 1024).expect("machine");

        // No keys pressed, 50 Hz strap, EAR idle high: the historical 0xFF.
        assert_eq!(machine.read_keyboard_port(0x00), 0xFF);

        machine.set_television_standard(TelevisionStandard::SixtyHz);
        assert_eq!(
            machine.read_keyboard_port(0x00),
            0xBF,
            "a 60 Hz strap must pull bit 6 low and touch nothing else",
        );

        machine.set_ear_input(false);
        assert_eq!(
            machine.read_keyboard_port(0x00),
            0x3F,
            "a low EAR line must pull bit 7 low and touch nothing else",
        );

        machine.set_television_standard(TelevisionStandard::FiftyHz);
        assert_eq!(machine.read_keyboard_port(0x00), 0x7F);

        // Bit 5 is never driven low.
        for standard in [TelevisionStandard::FiftyHz, TelevisionStandard::SixtyHz] {
            machine.set_television_standard(standard);
            assert_eq!(machine.read_keyboard_port(0x00) & 0x20, 0x20);
        }
    }

    /// The window follows the board strap, buffer and placement together.
    ///
    /// This is #1119. `FB_HEIGHT` was a plain `const` at 288 for every ZX81,
    /// so a 60 Hz board painted into a PAL-sized buffer while its runtime
    /// declared a 240-line one, and `FIRST_TEXT_LINE` was the 50 Hz figure so
    /// the picture sat high in it as well. Nothing failed: nothing asserted
    /// the NTSC picture at all, and the 50 Hz path the goldens exercise was
    /// right. That is why this asserts the pair rather than the height alone.
    #[test]
    fn the_window_follows_the_board_strap() {
        let mut machine = Zx81::new(trap_rom(), 1024).expect("machine");
        let width = machine.framebuffer_width();

        assert_eq!(
            machine.framebuffer_height(),
            288,
            "a 50 Hz board scans a PAL set"
        );
        assert_eq!(
            machine.text_top(),
            48,
            "and centres 192 lines of text in it"
        );

        machine.set_television_standard(TelevisionStandard::SixtyHz);
        assert_eq!(
            machine.framebuffer_height(),
            240,
            "a 60 Hz board scans an NTSC set"
        );
        assert_eq!(
            machine.text_top(),
            24,
            "and its shorter pad centres the text in that"
        );

        assert_eq!(
            machine.framebuffer().len(),
            (width * 240) as usize,
            "the buffer itself has to be reallocated, or the height is a claim \
             about a buffer that is still the other region's size"
        );

        machine.set_television_standard(TelevisionStandard::FiftyHz);
        assert_eq!(machine.framebuffer_height(), 288, "and back");
        assert_eq!(machine.framebuffer().len(), (width * 288) as usize);
    }

    /// The keyboard bits still work, and the upper bits do not disturb them.
    #[test]
    fn the_strap_does_not_disturb_the_keyboard_bits() {
        let mut machine = Zx81::new(trap_rom(), 1024).expect("machine");
        machine.press_key(Zx81Key::Shift);
        let fifty = machine.read_keyboard_port(0xFE) & 0x1F;

        machine.set_television_standard(TelevisionStandard::SixtyHz);
        machine.set_ear_input(false);
        assert_eq!(machine.read_keyboard_port(0xFE) & 0x1F, fifty);
        assert_ne!(fifty, 0x1F, "Shift should read as a pressed key");
    }
}

/// One captured I/O port access, for the debug trace.
#[derive(Debug, Clone, Copy)]
pub struct IoEvent {
    /// CPU program counter at the time of the access.
    pub pc: u16,
    /// I/O port — the full 16-bit address bus.
    ///
    /// The ZX81 decodes its keyboard on the **high** byte: `IN A,($FE)`
    /// selects the row from `A15`-`A8`, so a trace that kept only the low
    /// byte could not say which row was scanned. Fixed in #926.
    pub port: u16,
    /// Byte written, or byte returned on a read.
    pub value: u8,
    /// `true` for `OUT`, `false` for `IN`.
    pub write: bool,
}

impl Zx81 {
    /// Observe one byte on the bus without side effects.
    #[must_use]
    pub fn peek(&self, addr: u16) -> u8 {
        self.mem_read(addr)
    }

    /// Write one byte through the bus (RAM accepts it; ROM ignores it).
    pub fn poke(&mut self, addr: u16, value: u8) {
        self.mem_write(addr, value);
    }

    /// Start (or restart) the I/O port-access trace.
    pub fn start_io_trace(&mut self) {
        self.io_trace = Some(Vec::new());
    }

    /// Stop tracing and return the captured I/O events.
    pub fn take_io_trace(&mut self) -> Vec<IoEvent> {
        self.io_trace.take().unwrap_or_default()
    }
}
