[package]
name = "machine-sinclair-zx-spectrum-48k"
description = "ZX Spectrum 48K machine state and $FE I/O surface"
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
common-sinclair-zx-spectrum = { path = "../common-sinclair-zx-spectrum", version = "0.17.0" }
common-sinclair-zx-spectrum-48k-class = { path = "../common-sinclair-zx-spectrum-48k-class", version = "0.17.0" }
emu198x-shell = { path = "../emu198x-shell", version = "0.17.0" }
ferranti-ula-6c001e = { path = "../ferranti-ula-6c001e", version = "0.17.0" }
peripheral-kempston-joystick = { path = "../peripheral-kempston-joystick", version = "0.17.0" }
serde = { workspace = true }
emu198x-zilog-z80 = { path = "../emu198x-zilog-z80", version = "0.6.0" }

[dev-dependencies]
emu198x-test-skip = { path = "../emu198x-test-skip", version = "0.17.0" }
format198x-sinclair-zx-spectrum-tap = "0.1.1"
png = { workspace = true }

[lints]
workspace = true
