[package]
name = "ti-tms9918"
description = "Texas Instruments TMS9918A/9928A/9929A Video Display Processor"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
serde-big-array = { workspace = true }

[lints]
workspace = true
