[package]
name = "common-sinclair-zx-spectrum"
description = "Shared Spectrum-family hardware building blocks"
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
common-tape = { path = "../common-tape", version = "0.22.0" }
format-sinclair-zx-spectrum-snapshot = { path = "../format-sinclair-zx-spectrum-snapshot", version = "0.22.0" }
gi-ay-3-8912 = { path = "../gi-ay-3-8912", version = "0.22.0" }
serde = { workspace = true }
serde-big-array = { workspace = true }
thiserror = { workspace = true }
emu198x-zilog-z80 = { path = "../emu198x-zilog-z80", version = "0.6.0" }

[lints]
workspace = true
