[package]
name = "emu198x-acorn-atom"
description = "Acorn Atom headless runner"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "emu198x-acorn-atom"
path = "src/main.rs"

[dependencies]
machine-acorn-atom = { path = "../machine-acorn-atom" }
png = { workspace = true }

[lints]
workspace = true
