//! Fixture-free proof that the machine starts.
//!
//! The Oric needs its manufacturer's ROM to reach a prompt, and that ROM
//! cannot be copied to a public runner. So this asks the weaker question CI
//! *can* answer: put code this project wrote in the ROM socket, and see
//! whether the machine runs it.
//!
//! A pass proves the reset vector was fetched, the ROM is readable where the
//! memory map says it is, the CPU executed, the ULA fetched the video RAM
//! that was written, and a frame reached the framebuffer. It does **not**
//! prove the real firmware boots.
//!
//! The Oric has no background register to write. Colour lives in the text
//! stream as attribute bytes, so the program fills video RAM at `$BB80` with
//! a paper attribute and every cell becomes background.
//!
//! The image is generated by
//! `test-data/synthetic-firmware/build-synthetic-firmware.py`.

use std::path::PathBuf;

use machine_oric_atmos::{OricAtmos, OricModel};

/// What paper attribute `$16` renders — paper 6. The power-on frame is
/// black, so this cannot appear unless the firmware ran.
const PAPER: u32 = 0xFF00_FFFF;

fn firmware(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../test-data/synthetic-firmware")
        .join(name)
}

fn booted(name: &str) -> OricAtmos {
    let rom = std::fs::read(firmware(name)).expect("firmware image");
    let mut machine = OricAtmos::new(rom, OricModel::Atmos);
    for _ in 0..10 {
        machine.run_frame();
    }
    machine
}

#[test]
fn synthetic_firmware_runs_and_floods_the_display() {
    let machine = booted("oric-atmos.rom");
    let framebuffer = machine.framebuffer();
    assert!(
        framebuffer.iter().all(|&pixel| pixel == PAPER),
        "every cell is a paper attribute, so the whole frame should be paper 6"
    );
}

/// The control image spins without writing video RAM.
#[test]
fn the_control_image_renders_no_paper_at_all() {
    let machine = booted("oric-atmos-control.rom");
    assert_eq!(
        machine
            .framebuffer()
            .iter()
            .filter(|&&p| p == PAPER)
            .count(),
        0,
        "a machine that ran no firmware must not show the firmware's colour"
    );
}
