[package]
name = "machine-mattel-aquarius"
description = "Mattel Aquarius machine wiring — Z80 + memory-mapped char display"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
emu198x-zilog-z80 = { path = "../emu198x-zilog-z80", version = "0.6.0" }
emu198x-gi-ay-3-8910 = { path = "../emu198x-gi-ay-3-8910", version = "0.6.0" }
serde = { workspace = true }
serde-big-array = { workspace = true }

[dev-dependencies]
postcard = { workspace = true }

[lints]
workspace = true
