[package]
name = "runtime-coleco-colecovision"
description = "Coleco ColecoVision family metadata and headless runtime wrapper around machine-coleco-colecovision"
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
emu198x-shell = { path = "../emu198x-shell", version = "0.22.0" }
ti-tms9918 = { path = "../ti-tms9918", version = "0.22.0" }
machine-coleco-colecovision = { path = "../machine-coleco-colecovision", version = "0.22.0" }
emu198x-zilog-z80 = { path = "../emu198x-zilog-z80", version = "0.6.0" }
postcard = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
