[package]
name = "runtime-coleco-colecovision"
description = "Coleco ColecoVision family metadata and headless runtime wrapper around machine-coleco-colecovision"
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
emu198x-shell = { path = "../emu198x-shell", version = "0.2.0" }
machine-coleco-colecovision = { path = "../machine-coleco-colecovision", version = "0.2.0" }
zilog-z80 = { path = "../zilog-z80", version = "0.2.0" }
postcard = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
