//! CRC32s of the Atari 8-bit cartridges built on OSS banking boards.
//!
//! Generated by `tools/a800-oss-cart-types.py` from MAME's `a800.xml`
//! software list (CC0-1.0). Do not edit by hand -- rerun the script.
//!
//! A headerless image whose CRC32 appears here gets the listed board; every
//! other headerless image keeps the plain layout its size implies. See
//! `knowledge/decisions/cart-layout-needs-positive-evidence.md`.

use crate::CartridgeKind;

/// Sorted by CRC32 for `binary_search_by_key`.
pub(crate) const OSS_CRC32: [(u32, CartridgeKind); 14] = [
    // Basic XE Programming Language v4.1
    (0x003D_3A36, CartridgeKind::OssOneChip),
    // The Writer's Tool
    (0x13BC_F201, CartridgeKind::OssEightK),
    // Basic XE Programming Language v7.2
    (0x3F06_B111, CartridgeKind::OssOneChip),
    // MAC-65 Macro Assembler v1.01
    (0x4102_CA4F, CartridgeKind::OssOneChip),
    // ACE-80XL: Eighty Column Display for Atari Computers v1.1
    (0x4D14_8A37, CartridgeKind::OssOneChip),
    // MAC-65 Macro Assembler v1.02
    (0x5193_1A08, CartridgeKind::OssTwoChipLegacy),
    // Basic XL Programming Language v1.02 (alt)
    (0x5752_D29F, CartridgeKind::OssTwoChip),
    // MAC-65 Macro Assembler v1.00
    (0x5E03_3719, CartridgeKind::OssTwoChip),
    // Spectraview II
    (0x77C7_5598, CartridgeKind::OssTwoChipLegacy),
    // Basic XL Programming Language v1.03
    (0x94A0_5568, CartridgeKind::OssOneChip),
    // Action! Programming Language v3.6
    (0xA1F9_0DFD, CartridgeKind::OssOneChip),
    // Action! Programming Language v3.5
    (0xAE29_8A33, CartridgeKind::OssTwoChip),
    // Basic XL Programming Language v1.02
    (0xE8B3_FC3C, CartridgeKind::OssTwoChipLegacy),
    // Action! Programming Language v3.6 (alt)
    (0xEB90_5CB4, CartridgeKind::OssTwoChipLegacy),
];
