[package]
name = "emu198x-amiga"
description = "Minimal native Amiga verifier shell"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
emu198x-shell = { path = "../emu198x-shell" }
pixels.workspace = true
runtime-commodore-amiga = { path = "../runtime-commodore-amiga" }
thiserror.workspace = true
winit.workspace = true

[lints]
workspace = true
