[package]
name = "peripheral-commodore-amiga-floppy"
description = "Amiga floppy drive mechanism — head positioning, motor control, disk change detection, MFM track encoding."
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
format198x-commodore-amiga-adf = "0.3.0"
serde = { workspace = true }

[lints]
workspace = true
