[package]
name = "sega-vdp"
description = "Sega Master System / Game Gear VDP (315-5124 / 315-5246)"
version = "0.2.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
serde-big-array = { workspace = true }

[lints]
workspace = true
