[package]
name = "commodore-denise-ocs"
description = "Commodore Denise OCS — pixel shifter and sprite engine. Bitplane-to-pixel conversion, playfield composition, 8 sprites, palette lookup."
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
serde-big-array = { workspace = true }

[lints]
workspace = true
