[package]
name = "format-commodore-amiga-adf"
description = "Amiga Disk File (ADF) image parser — 80 cylinders × 2 heads × 11/22 sectors × 512 bytes."
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]

[lints]
workspace = true
