[package]
name = "format-amstrad-dsk"
description = "DSK and EDSK floppy image parser — used by the Amstrad CPC and ZX Spectrum +3"
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
nec-upd765a = { path = "../nec-upd765a", version = "0.20.0" }

[lints]
workspace = true
