//! Fixture-free proof that the machine starts.
//!
//! The ZX81 needs its manufacturer's ROM to reach a prompt, and that ROM
//! cannot be copied to a public runner — and unlike the Spectrum it is not
//! covered by Amstrad's permission, which stops at the machines Amstrad
//! actually bought. Its rights sit with Nine Tiles. So synthetic firmware is
//! not merely the cheap route here, it is the only one available.
//!
//! ## What a pass proves, stated carefully
//!
//! On real hardware the **CPU** generates the picture: the Z80 executes
//! through the display file while the ULA forces NOPs and turns the fetched
//! bytes into video. Since #1032 this emulator models exactly that, and the
//! firmware below does what the hardware requires — it runs a display
//! routine driven by the ULA's NMI line clock.
//!
//! So a pass proves the CPU reached the display file, executed it with bit
//! 15 of the address set, and that the ULA forced each byte to a `NOP`,
//! latched it, composed a pattern address from `I` and its own line counter,
//! and shifted eight pixels out at the beam — 49,152 of them, in the right
//! place. Before #1032 this proved considerably less: the ULA read the
//! `D_FILE` pointer at frame boundaries and drew the screen itself, so an
//! image that merely *wrote* a display file passed.
//!
//! ## The firmware never writes `D_FILE`
//!
//! Deliberately. `$400C` stays zero, so the frame-boundary renderer this
//! replaced would have found nothing to draw — which is the assertion at the
//! end of the first test, and the sharpest thing here. A picture appearing
//! with the pointer unset can only have come from the bus.
//!
//! ## The firmware has to point `I` at a character set
//!
//! Character bitmaps live at `I << 8 | char << 3 | line`, as on hardware, so
//! nothing legible appears until the firmware sets `I`. This image sets it to
//! the page the real ROM uses, and the ROM is zero-filled there — so glyph 0
//! is blank, and the display file is written with `$80`: glyph 0 *inverted*,
//! solid only because inverting a blank bitmap sets every pixel.
//!
//! That makes the test depend on three separate things the firmware must do —
//! setting `I`, writing the display file, and executing it — and on none of
//! them being true by accident. A glyph already solid in ROM would light the
//! screen with the CPU switched off, which is the trap the PET's character
//! ROM avoids the same way.
//!
//! The image is generated by
//! `test-data/synthetic-firmware/build-synthetic-firmware.py` from
//! `sinclair-zx81-display.asm` beside it, which carries the timing notes.

use std::path::PathBuf;

use machine_sinclair_zx81::Zx81;

/// Ink.
const INK: u32 = 0xFF00_0000;

fn firmware(name: &str) -> Vec<u8> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../test-data/synthetic-firmware")
        .join(name);
    std::fs::read(path).expect("firmware image")
}

fn booted(name: &str) -> Zx81 {
    let mut machine = Zx81::new(firmware(name), 16 * 1024).expect("synthetic ROM should init");
    for _ in 0..20 {
        machine.run_frame();
    }
    machine
}

#[test]
fn synthetic_firmware_writes_a_display_file_the_ula_renders() {
    let machine = booted("sinclair-zx81.rom");
    let ink = machine
        .framebuffer()
        .iter()
        .filter(|&&pixel| pixel == INK)
        .count();
    // 49,152 in practice — 256x192, exactly 32x24 characters. The rest is
    // border, which a display file cannot reach.
    assert!(
        ink > machine.framebuffer().len() / 2,
        "the CPU should have drawn the display file as solid ink; got {ink} of {} pixels",
        machine.framebuffer().len()
    );

    // The sharp one. The firmware never writes the D_FILE pointer, so the
    // frame-boundary renderer this replaced would have had nothing to draw
    // from. A full screen with $400C still zero can only have come off the
    // bus (#1032).
    let d_file =
        u16::from(machine.peek_memory(0x400C)) | u16::from(machine.peek_memory(0x400D)) << 8;
    assert_eq!(
        d_file, 0,
        "the picture must not be reachable through the D_FILE pointer"
    );
}

/// The control image spins without setting `D_FILE`, which therefore stays
/// zero and points the ULA at ROM. That renders a little scattered ink —
/// about 5% of the frame — rather than nothing, so this asserts a ceiling
/// rather than an absence. The gap between 5% and 64% is the signal.
#[test]
fn the_control_image_renders_no_display_file() {
    let machine = booted("sinclair-zx81-control.rom");
    let ink = machine
        .framebuffer()
        .iter()
        .filter(|&&pixel| pixel == INK)
        .count();
    assert!(
        ink < machine.framebuffer().len() / 8,
        "a machine that never set D_FILE cannot fill the display; got {ink} pixels"
    );
}
