//! Fixture-free proof that the machine starts.
//!
//! The ZX81 needs its manufacturer's ROM to reach a prompt, and that ROM
//! cannot be copied to a public runner — and unlike the Spectrum it is not
//! covered by Amstrad's permission, which stops at the machines Amstrad
//! actually bought. Its rights sit with Nine Tiles. So synthetic firmware is
//! not merely the cheap route here, it is the only one available.
//!
//! ## What a pass proves, stated carefully
//!
//! On real hardware the **CPU** generates the picture: the Z80 executes
//! through the display file while the ULA forces NOPs and turns the fetched
//! bytes into video. Since #1032 this emulator models exactly that, and the
//! firmware below does what the hardware requires — it runs a display
//! routine driven by the ULA's NMI line clock.
//!
//! So a pass proves the CPU reached the display file, executed it with bit
//! 15 of the address set, and that the ULA forced each byte to a `NOP`,
//! latched it, composed a pattern address from `I` and its own line counter,
//! and shifted eight pixels out at the beam — 49,152 of them, in the right
//! place. Before #1032 this proved considerably less: the ULA read the
//! `D_FILE` pointer at frame boundaries and drew the screen itself, so an
//! image that merely *wrote* a display file passed.
//!
//! ## The firmware never writes `D_FILE`
//!
//! Deliberately. `$400C` stays zero, so the frame-boundary renderer this
//! replaced would have found nothing to draw — which is the assertion at the
//! end of the first test, and the sharpest thing here. A picture appearing
//! with the pointer unset can only have come from the bus.
//!
//! ## The firmware has to point `I` at a character set
//!
//! Character bitmaps live at `I << 8 | char << 3 | line`, as on hardware, so
//! nothing legible appears until the firmware sets `I`. This image sets it to
//! the page the real ROM uses, and the ROM is zero-filled there — so glyph 0
//! is blank, and the display file is written with `$80`: glyph 0 *inverted*,
//! solid only because inverting a blank bitmap sets every pixel.
//!
//! That makes the test depend on three separate things the firmware must do —
//! setting `I`, writing the display file, and executing it — and on none of
//! them being true by accident. A glyph already solid in ROM would light the
//! screen with the CPU switched off, which is the trap the PET's character
//! ROM avoids the same way.
//!
//! ## A second image, for the keyboard
//!
//! `sinclair-zx81-keyboard.rom` scans the matrix itself and puts one
//! character row on screen per keyboard row. #1041 — the ZX81 ignoring every
//! key — could only be caught end to end, and the test that pins it needs
//! Sinclair's ROM, which cannot be staged on a runner. This is the part that
//! can, and it asserts row *selection* rather than merely that a key
//! registered.
//!
//! Both images are generated by
//! `test-data/synthetic-firmware/build-synthetic-firmware.py` from
//! `sinclair-zx81-display.asm` and `sinclair-zx81-keyboard.asm` beside it,
//! which carry the timing notes.

use std::path::PathBuf;

use machine_sinclair_zx81::{Zx81, Zx81Key};

/// Ink.
const INK: u32 = 0xFF00_0000;

fn firmware(name: &str) -> Vec<u8> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../test-data/synthetic-firmware")
        .join(name);
    std::fs::read(path).expect("firmware image")
}

fn booted(name: &str) -> Zx81 {
    let mut machine = Zx81::new(firmware(name), 16 * 1024).expect("synthetic ROM should init");
    for _ in 0..20 {
        machine.run_frame();
    }
    machine
}

#[test]
fn synthetic_firmware_writes_a_display_file_the_ula_renders() {
    let machine = booted("sinclair-zx81.rom");
    let ink = machine
        .framebuffer()
        .iter()
        .filter(|&&pixel| pixel == INK)
        .count();
    // 49,152 in practice — 256x192, exactly 32x24 characters. The rest is
    // border, which a display file cannot reach.
    assert!(
        ink > machine.framebuffer().len() / 2,
        "the CPU should have drawn the display file as solid ink; got {ink} of {} pixels",
        machine.framebuffer().len()
    );

    // The sharp one. The firmware never writes the D_FILE pointer, so the
    // frame-boundary renderer this replaced would have had nothing to draw
    // from. A full screen with $400C still zero can only have come off the
    // bus (#1032).
    let d_file =
        u16::from(machine.peek_memory(0x400C)) | u16::from(machine.peek_memory(0x400D)) << 8;
    assert_eq!(
        d_file, 0,
        "the picture must not be reachable through the D_FILE pointer"
    );
}

/// The control image spins without setting `D_FILE`, which therefore stays
/// zero and points the ULA at ROM. That renders a little scattered ink —
/// about 5% of the frame — rather than nothing, so this asserts a ceiling
/// rather than an absence. The gap between 5% and 64% is the signal.
#[test]
fn the_control_image_renders_no_display_file() {
    let machine = booted("sinclair-zx81-control.rom");
    let ink = machine
        .framebuffer()
        .iter()
        .filter(|&&pixel| pixel == INK)
        .count();
    assert!(
        ink < machine.framebuffer().len() / 8,
        "a machine that never set D_FILE cannot fill the display; got {ink} pixels"
    );
}

/// Which eight-line character bands are solid.
fn lit_bands(machine: &Zx81) -> Vec<usize> {
    let frame = machine.framebuffer();
    let width = machine.framebuffer_width() as usize;
    (0..24)
        .filter(|row| {
            let y = machine.text_top() as usize + row * 8 + 3;
            (0..256)
                .filter(|x| frame[y * width + 32 + x] == INK)
                .count()
                > 200
        })
        .collect()
}

/// Run the keyboard image with `keys` held, and report which bands light.
fn bands_with(keys: &[Zx81Key]) -> Vec<usize> {
    let mut machine =
        Zx81::new(firmware("sinclair-zx81-keyboard.rom"), 16 * 1024).expect("synthetic ROM");
    for key in keys {
        machine.press_key(*key);
    }
    for _ in 0..12 {
        machine.run_frame();
    }
    lit_bands(&machine)
}

/// #1041, on a runner.
///
/// That issue was the ZX81 ignoring every key, and the test that pins it needs
/// Sinclair's ROM — which cannot be staged in CI, so the keyboard was left
/// unguarded there. This image closes that: it scans the matrix itself and
/// puts one character row on screen per keyboard row.
///
/// Row *selection* is what this asserts, not merely that a key registered. A
/// machine that returned the same byte for every row — the shape a broken
/// `RLC B` walk would give — would light the wrong band or all of them, and a
/// test that only counted ink would pass it happily.
#[test]
fn each_keyboard_row_lights_its_own_character_row() {
    assert!(
        bands_with(&[]).is_empty(),
        "nothing should be lit with no key held"
    );

    for (row, key) in [
        Zx81Key::Shift,
        Zx81Key::A,
        Zx81Key::Q,
        Zx81Key::N1,
        Zx81Key::N0,
        Zx81Key::P,
        Zx81Key::Newline,
        Zx81Key::Space,
    ]
    .into_iter()
    .enumerate()
    {
        assert_eq!(
            bands_with(&[key]),
            vec![row],
            "{key:?} is in keyboard row {row} and should light that row alone"
        );
    }
}

/// The other half of "it is really reading rows": a second key in the *same*
/// row adds nothing, and one in a different row adds exactly one band.
///
/// `Shift` and `V` are both row 0; `G` is row 1. Without this a machine that
/// merged every row into one answer could still pass the test above, by
/// lighting whichever row it happened to attribute the key to.
#[test]
fn two_keys_light_one_band_or_two_by_their_rows() {
    assert_eq!(
        bands_with(&[Zx81Key::Shift, Zx81Key::V]),
        vec![0],
        "two keys in row 0 are still one row"
    );
    assert_eq!(
        bands_with(&[Zx81Key::Shift, Zx81Key::G]),
        vec![0, 1],
        "a key in row 0 and one in row 1 are two rows"
    );
    assert_eq!(
        bands_with(&[Zx81Key::V, Zx81Key::G, Zx81Key::Space]),
        vec![0, 1, 7],
        "three rows, three bands"
    );
}
