[package]
name = "emu198x-c64"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
common-commodore-c64 = { path = "../common-commodore-c64" }
emu198x-native-video = { path = "../emu198x-native-video" }
emu198x-shell = { path = "../emu198x-shell" }
runtime-commodore-c64 = { path = "../runtime-commodore-c64" }
thiserror.workspace = true
winit.workspace = true

[lints]
workspace = true
