[package]
name = "format-sinclair-zx-spectrum-sna"
description = ".sna snapshot format parser for the ZX Spectrum"
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
format-sinclair-zx-spectrum-snapshot = { path = "../format-sinclair-zx-spectrum-snapshot", version = "0.21.0" }

[lints]
workspace = true
