[package]
name = "atari-pokey"
description = "Atari POKEY sound + I/O chip — Atari 5200, 7800, 800XL, 130XE"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
serde-big-array = { workspace = true }

[lints]
workspace = true
