[package]
name = "mos-6502"
description = "MOS 6502 CPU with a cycle-accurate pin-level bus interface"
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }

[dev-dependencies]
emu198x-test-skip = { path = "../emu198x-test-skip", version = "0.4.0" }
serde_json = { workspace = true }

[lints]
workspace = true
