[package]
name = "mos-6502"
description = "MOS 6502 CPU with a cycle-accurate pin-level bus interface"
edition.workspace = true
version = "0.2.0"
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
