[package]
name = "runtime-sega-master-system"
description = "Sega Master System machine profiles and runtime constructors"
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
emu198x-shell = { path = "../emu198x-shell", version = "0.10.0" }
machine-sega-master-system = { path = "../machine-sega-master-system", version = "0.10.0" }
runtime-sega-master-system-class = { path = "../runtime-sega-master-system-class", version = "0.10.0" }

[dev-dependencies]
sega-vdp = { path = "../sega-vdp", version = "0.10.0" }
serde_json = { workspace = true }
emu198x-zilog-z80 = { path = "../emu198x-zilog-z80", version = "0.6.0" }

[lints]
workspace = true
