[package]
name = "atari-gtia"
description = "Atari GTIA video output chip — Atari 5200, 800XL, 130XE"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
serde-big-array = { workspace = true }

[lints]
workspace = true
