[package]
name = "runtime-sord-m5"
description = "Sord M5 family metadata and headless runtime wrapper"
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
emu198x-shell = { path = "../emu198x-shell", version = "0.19.0" }
ti-tms9918 = { path = "../ti-tms9918", version = "0.19.0" }
machine-sord-m5 = { path = "../machine-sord-m5", version = "0.19.0" }
emu198x-zilog-z80 = { path = "../emu198x-zilog-z80", version = "0.6.0" }
postcard = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
