//! Phase 1 characterization tests — Serial Data Register (SDR) + SP/CNT.
//!
//! Per HRM Appendix F p.345:
//!   - SDR at $C is an 8-bit shift register
//!   - CRA bit 6 = 0 → SDR is input, shifted in from SP on CNT edges
//!   - CRA bit 6 = 1 → SDR is output, shifted out on SP with CNT
//!     generated by Timer A underflow
//!   - Either direction: byte-complete latches ICR bit 3 (SP)
//!
//! Amiga use:
//!   - CIA-A SP pin = keyboard data line; CNT pin = keyboard clock
//!   - CIA-B SP/CNT unused by Kickstart
//!
//! The archive exposes `receive_serial_byte(byte)` as a whole-byte
//! shortcut — sufficient for keyboard-scancode delivery. Bit-level
//! shifting is not implemented in the archive and is out of scope
//! for Phase 1.

use mos_cia_8520::Cia8520;

const CRA: u8 = 0x0E;
const SDR: u8 = 0x0C;
const ICR: u8 = 0x0D;

const ICR_SP: u8 = 0x08;

// ────────────────────────────────────────────────────────────────
// SDR register read/write storage
// ────────────────────────────────────────────────────────────────

#[test]
fn sdr_register_is_directly_readable_and_writeable() {
    let mut cia = Cia8520::new("T");
    cia.write(SDR, 0xA5);
    assert_eq!(cia.read(SDR), 0xA5);
    cia.write(SDR, 0x42);
    assert_eq!(cia.read(SDR), 0x42);
}

#[test]
fn sdr_reset_value_is_zero() {
    let mut cia = Cia8520::new("T");
    cia.write(SDR, 0xFF);
    cia.reset();
    assert_eq!(cia.read(SDR), 0);
}

// ────────────────────────────────────────────────────────────────
// Byte-complete interrupt (ICR bit 3 = SP)
// ────────────────────────────────────────────────────────────────

#[test]
fn receive_byte_helper_stores_byte_and_latches_sp_flag() {
    let mut cia = Cia8520::new("T");
    cia.receive_serial_byte(0xA5);
    assert_eq!(cia.read(SDR), 0xA5, "byte stored in SDR");
    assert_ne!(cia.icr_status() & ICR_SP, 0, "SP flag latched on byte complete");
}

#[test]
fn sp_flag_persists_until_icr_read() {
    let mut cia = Cia8520::new("T");
    cia.receive_serial_byte(0x01);
    assert_ne!(cia.icr_status() & ICR_SP, 0);
    // Ticking shouldn't clear it
    for _ in 0..100 {
        cia.tick();
    }
    assert_ne!(cia.icr_status() & ICR_SP, 0);
    // ICR read clears
    let _ = cia.read(ICR);
    assert_eq!(cia.icr_status() & ICR_SP, 0);
}

#[test]
fn sp_flag_masked_does_not_assert_irq() {
    let mut cia = Cia8520::new("T");
    cia.receive_serial_byte(0x01);
    assert!(!cia.irq_active(), "no IRQ when SP mask bit is clear");
    assert_ne!(cia.icr_status() & ICR_SP, 0, "flag latches regardless of mask");
}

#[test]
fn sp_flag_unmasked_asserts_irq() {
    let mut cia = Cia8520::new("T");
    cia.write(ICR, 0x88); // SET mask bit 3 (SP)
    cia.receive_serial_byte(0x01);
    assert!(cia.irq_active(), "IRQ active when SP is unmasked + flagged");

    // ICR read clears flag, drops IRQ
    let ret = cia.read(ICR);
    assert_eq!(ret & 0x80, 0x80, "IR bit set in read value");
    assert_eq!(ret & ICR_SP, ICR_SP, "SP bit set in read value");
    assert!(!cia.irq_active(), "IRQ clears after ICR read");
}

// ────────────────────────────────────────────────────────────────
// Mode bit (CRA bit 6) round-trips
// ────────────────────────────────────────────────────────────────

#[test]
fn cra_bit_6_persists_in_read_back() {
    let mut cia = Cia8520::new("T");
    cia.write(CRA, 0x40); // SPMODE = 1 (output)
    assert_eq!(cia.read(CRA) & 0x40, 0x40);
    cia.write(CRA, 0x00);
    assert_eq!(cia.read(CRA) & 0x40, 0x00);
}

// ────────────────────────────────────────────────────────────────
// Multiple bytes in sequence — each re-latches SP
// ────────────────────────────────────────────────────────────────

#[test]
fn consecutive_bytes_each_latch_sp_after_icr_clear() {
    let mut cia = Cia8520::new("T");
    cia.write(ICR, 0x88);
    cia.receive_serial_byte(0x01);
    assert!(cia.irq_active());
    let _ = cia.read(ICR); // clear
    assert!(!cia.irq_active());

    cia.receive_serial_byte(0x02);
    assert!(cia.irq_active(), "second byte re-latches SP");
    assert_eq!(cia.read(SDR), 0x02, "SDR shows latest byte");
}

// ────────────────────────────────────────────────────────────────
// SDR + SP-flag interaction with reset
// ────────────────────────────────────────────────────────────────

#[test]
fn reset_clears_sp_flag_and_sdr_but_not_icr_mask() {
    let mut cia = Cia8520::new("T");
    cia.write(ICR, 0x88); // unmask SP
    cia.receive_serial_byte(0xFF);
    assert_ne!(cia.icr_status() & ICR_SP, 0);
    cia.reset();
    assert_eq!(cia.icr_status(), 0, "reset clears ICR status");
    assert_eq!(cia.read(SDR), 0, "reset clears SDR");
    assert_eq!(
        cia.icr_mask(),
        0,
        "reset clears mask per HRM §F reset table"
    );
}
