//! Fixture-free proof that the machine starts.
//!
//! The Electron needs its manufacturer's ROM to reach a prompt, and that ROM
//! cannot be copied to a public runner. So this asks the weaker question CI
//! *can* answer: put code this project wrote in the ROM socket, and see
//! whether the machine runs it. It does **not** prove the real firmware
//! boots.
//!
//! ## Why this writes the palette instead of the screen
//!
//! The ULA powers on with all eight palette registers at `$FF`, which
//! decodes to **all sixteen logical colours white**. Filling screen RAM
//! therefore proves nothing — attempts with `$FF` and with `$00` both left
//! the frame 100% white, because the content was invisible rather than
//! unwritten. The failure looks identical to a machine that never ran.
//!
//! Writing the palette avoids the screen entirely: with every logical colour
//! mapped to red, whatever uninitialised RAM holds, the frame comes out red.
//!
//! The mapping is scrambled. The ULA stores each register inverted
//! (`written EOR $FF`) and draws one colour's red, green and blue from
//! individual, non-contiguous bits of a register *pair*. The values here
//! were derived by working backwards through this crate's own
//! `decode_palette`, not guessed.
//!
//! The image is generated by
//! `test-data/synthetic-firmware/build-synthetic-firmware.py`.

use std::path::PathBuf;

use machine_acorn_electron::AcornElectron;

/// Every logical colour mapped to physical red.
const RED: u32 = 0xFFFF_0000;
/// What the ULA shows having been programmed by nobody.
const POWER_ON: u32 = 0xFFFF_FFFF;

fn firmware(name: &str) -> Vec<u8> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../test-data/synthetic-firmware")
        .join(name);
    std::fs::read(path).expect("firmware image")
}

fn booted(os: &str) -> AcornElectron {
    let mut machine = AcornElectron::new(firmware(os), firmware("acorn-electron-basic.rom"));
    for _ in 0..20 {
        machine.run_frame();
    }
    machine
}

#[test]
fn synthetic_firmware_reprogrammes_the_palette() {
    let machine = booted("acorn-electron.rom");
    assert!(
        machine.framebuffer().iter().all(|&pixel| pixel == RED),
        "every logical colour is mapped to red, so the frame should be uniform"
    );
}

/// The control image spins without touching the palette. It stays at the
/// all-white power-on state — which is *why* a screen fill proves nothing
/// here, and why this test pins the power-on colour rather than just
/// checking red is absent.
#[test]
fn the_control_image_stays_at_power_on_white() {
    let machine = booted("acorn-electron-control.rom");
    assert!(
        machine.framebuffer().iter().all(|&pixel| pixel == POWER_ON),
        "an unprogrammed ULA maps every logical colour to white"
    );
}
