"""Execute unmodified vAmiga period latch/reload bodies with a clock recorder."""

import argparse
import hashlib
import json
import subprocess
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--source", type=Path, required=True)
parser.add_argument("--output", type=Path, required=True)
args = parser.parse_args()
root = args.source.resolve()
out = args.output.resolve()
out.mkdir(parents=True, exist_ok=True)
revision = subprocess.check_output(
    ["git", "rev-parse", "HEAD"], cwd=root, text=True
).strip()
if revision != "60fd1e6b69dcd77c9f44d1291bd37ec715362ab0":
    raise ValueError(f"unregistered vAmiga revision: {revision}")


def extract(path: Path, name: str) -> str:
    source = path.read_text()
    start = source.index("template <isize nr> void\nStateMachine<nr>::" + name + "(")
    brace = source.index("{", start)
    depth = 1
    end = brace + 1
    while depth:
        depth += (source[end] == "{") - (source[end] == "}")
        end += 1
    return source[start:end]


state = root / "Core/Components/Paula/Audio/StateMachine.cpp"
regs = root / "Core/Components/Paula/Audio/StateMachineRegs.cpp"
prefix = r"""
// SPDX-License-Identifier: GPL-3.0-only
// Extracted vAmiga methods: Copyright (C) Dirk W. Hoffmann.
// Scheduler recorder and driver: generated by reference.py.
#include <cstdint>
#include <iostream>
using isize = long; using u16 = uint16_t; using u64 = uint64_t;
#define logdebug(...)
#define DMA_CYCLES(n) (8ULL * (n))
enum { SLOT_CH0, SLOT_CH1, SLOT_CH2, SLOT_CH3, CHX_PERFIN };
struct ClockRecorder {
    u64 now = 0, due = 0;
    template<int slot> void scheduleRel(u64 delay, int) { due = now + delay; }
};
template<isize nr> struct StateMachine {
    u16 audperLatch = 124;
    ClockRecorder agnus;
    void pokeAUDxPER(u16 value);
    void percntrld();
};
"""
main = r"""
int main() {
    for (unsigned period : {0, 1, 2, 3, 60, 113, 123, 124, 125, 512, 65535}) {
        StateMachine<0> channel;
        channel.pokeAUDxPER(period);
        channel.percntrld();
        std::cout << "period," << period << "," << channel.agnus.due / 8 << "\n";
    }
    for (unsigned phase : {1, 61, 122, 123}) {
        for (unsigned replacement : {0, 1, 512}) {
            StateMachine<0> channel;
            channel.pokeAUDxPER(124);
            channel.percntrld();
            channel.agnus.now = phase * 8;
            channel.pokeAUDxPER(replacement);
            auto original_due = channel.agnus.due;
            channel.agnus.now = original_due;
            channel.percntrld();
            std::cout << "write," << phase << "," << replacement << ","
                      << original_due / 8 << "," << channel.agnus.due / 8 << "\n";
        }
    }
}
"""
(out / "reference.cpp").write_text(
    prefix + extract(regs, "pokeAUDxPER") + "\n" + extract(state, "percntrld") + main
)
subprocess.run(
    [
        "c++",
        "-std=c++20",
        "-Wall",
        "-Wextra",
        "-Werror",
        str(out / "reference.cpp"),
        "-o",
        str(out / "reference"),
    ],
    check=True,
)
result = subprocess.check_output([str(out / "reference")], text=True)
(out / "reference.csv").write_text(result)
(out / "source-hashes.json").write_text(
    json.dumps(
        {
            str(p.relative_to(root)): hashlib.sha256(p.read_bytes()).hexdigest()
            for p in [state, regs]
        },
        indent=2,
    )
    + "\n"
)
print(result)
