//! Fixture-free proof that the machine starts.
//!
//! The Atom needs its manufacturer's ROM to reach a prompt, and that ROM
//! cannot be copied to a public runner. So this asks the weaker question CI
//! *can* answer: put code this project wrote in the ROM socket, and see
//! whether the machine runs it.
//!
//! A pass proves the reset vector was fetched, the ROM is readable where the
//! memory map says it is, the CPU executed, the 6847 fetched the video RAM
//! that was written, and a frame reached the framebuffer. It does **not**
//! prove the real firmware boots.
//!
//! The image is generated by
//! `test-data/synthetic-firmware/build-synthetic-firmware.py`.
//!
//! Unlike the other synthetic-firmware machines, **the Atom's control image
//! does not render black.** A 6847 with no programming still paints its
//! alphanumeric screen, so "never ran" here is green-on-dark-green rather
//! than a blank frame. The assertion is therefore that a colour appears
//! which the control does not contain — not that the frame stopped being
//! black, which was never true.

use std::path::PathBuf;

use machine_acorn_atom::AcornAtom;

/// What a screen full of `$BF` renders: semigraphics-4, colour 3, all four
/// blocks lit. The control image never produces it.
const SEMIGRAPHICS: u32 = 0xFF6B_0F1B;

/// The 6847's active display, which is the only part of the frame it draws
/// into. Everything outside it is border.
const ACTIVE_WIDTH: usize = 256;
const ACTIVE_HEIGHT: usize = 192;

fn firmware(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../test-data/synthetic-firmware")
        .join(name)
}

fn booted(name: &str) -> AcornAtom {
    let rom = std::fs::read(firmware(name)).expect("firmware image");
    let mut machine = AcornAtom::new(rom, 32 * 1024);
    for _ in 0..10 {
        machine.run_frame();
    }
    machine
}

#[test]
fn synthetic_firmware_runs_and_fills_the_display() {
    let machine = booted("acorn-atom.rom");
    let lit = machine
        .framebuffer()
        .iter()
        .filter(|&&pixel| pixel == SEMIGRAPHICS)
        .count();

    // Against the active area, not the whole framebuffer. The 6847 draws
    // 256x192 and the rest is border it can never light, so a fraction of the
    // buffer measures the border's size as much as the picture's — this read
    // 54% of the buffer when the border was 25 lines and 46% once the machine
    // held the 288 a PAL set shows, without anything about the picture
    // changing.
    let active = ACTIVE_WIDTH * ACTIVE_HEIGHT;
    assert!(
        lit > active / 2,
        "the 6847 should fetch the semigraphics the firmware wrote; got {lit} of {active} \
         active pixels"
    );
}

/// The control image spins without writing video RAM. It still renders a
/// screen — that is what a 6847 does — but it cannot render *this* colour.
#[test]
fn the_control_image_renders_none_of_that_colour() {
    let machine = booted("acorn-atom-control.rom");
    assert_eq!(
        machine
            .framebuffer()
            .iter()
            .filter(|&&pixel| pixel == SEMIGRAPHICS)
            .count(),
        0,
        "a machine that ran no firmware must not show the firmware's colour"
    );
}
