[package]
name = "machine-acorn-bbc-micro"
description = "BBC Micro Model B machine wiring — 6502 + 6845 CRTC + Video ULA + 2x VIA + SN76489"
version = "0.2.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
common-acorn-cassette = { path = "../common-acorn-cassette", version = "0.2.0" }
mos-6502 = { path = "../mos-6502", version = "0.2.0" }
mos-via-6522 = { path = "../mos-via-6522", version = "0.2.0" }
motorola-6845 = { path = "../motorola-6845", version = "0.2.0" }
ti-sn76489 = { path = "../ti-sn76489", version = "0.2.0" }
serde = { workspace = true }
serde-big-array = { workspace = true }

[dev-dependencies]
format-acorn-uef = { path = "../format-acorn-uef", version = "0.2.0" }
postcard = { workspace = true }

[lints]
workspace = true
