[package]
name = "machine-acorn-bbc-micro"
description = "BBC Micro Model B machine wiring — 6502 + 6845 CRTC + Video ULA + 2x VIA + SN76489"
version = "0.2.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
mos-6502 = { path = "../mos-6502" }
mos-via-6522 = { path = "../mos-via-6522" }
motorola-6845 = { path = "../motorola-6845" }
ti-sn76489 = { path = "../ti-sn76489" }

[lints]
workspace = true
