[package]
name = "format-sinclair-zx-spectrum-tzx"
description = "TZX tape format parser for Sinclair ZX Spectrum media"
edition.workspace = true
version = "0.2.0"
license.workspace = true
repository.workspace = true

[dependencies]
common-sinclair-zx-spectrum = { path = "../common-sinclair-zx-spectrum" }

[lints]
workspace = true
