[package]
name = "format-sinclair-zx-spectrum-tzx"
description = "TZX tape format parser for Sinclair ZX Spectrum media"
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
format-tzx = { path = "../format-tzx", version = "0.2.0" }
common-sinclair-zx-spectrum = { path = "../common-sinclair-zx-spectrum", version = "0.2.0" }

[lints]
workspace = true
