"""Execute vAmiga audio transitions with a deterministic DMA and clock driver."""

import argparse
import gzip
import hashlib
import json
import subprocess
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--source", type=Path, required=True)
parser.add_argument("--output", type=Path, required=True)
args = parser.parse_args()
root = args.source.resolve()
out = args.output.resolve()
out.mkdir(parents=True, exist_ok=True)
revision = subprocess.check_output(
    ["git", "rev-parse", "HEAD"], cwd=root, text=True
).strip()
if revision != "60fd1e6b69dcd77c9f44d1291bd37ec715362ab0":
    raise ValueError(f"unregistered vAmiga revision: {revision}")


def extract(path: Path, name: str, result: str = "void") -> str:
    source = path.read_text()
    start = source.index(f"template <isize nr> {result}\nStateMachine<nr>::{name}(")
    brace = source.index("{", start)
    depth, end = 1, brace + 1
    while depth:
        depth += (source[end] == "{") - (source[end] == "}")
        end += 1
    return source[start:end]


state = root / "Core/Components/Paula/Audio/StateMachine.cpp"
regs = root / "Core/Components/Paula/Audio/StateMachineRegs.cpp"
header = root / "Core/Components/Paula/Audio/StateMachine.h"
prefix = r"""
// SPDX-License-Identifier: GPL-3.0-only
// Extracted vAmiga methods: Copyright (C) Dirk W. Hoffmann.
// Deterministic clock/DMA adapter generated by reference.py.
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <iostream>
using isize = long; using u16 = uint16_t; using u64 = uint64_t;
#define logdebug(...)
#define DMA_CYCLES(n) (8ULL * (n))
enum { SLOT_CH0, SLOT_CH1, SLOT_CH2, SLOT_CH3, CHX_PERFIN };
struct ClockRecorder {
    u64 now = 0, due = 0;
    template<int slot> void scheduleRel(u64 delay, int) { due = now + delay; }
};
struct Paula;
template<isize nr> struct StateMachine {
    Paula &paula;
    ClockRecorder agnus;
    u16 audperLatch = 777, audvolLatch = 7, audvol = 7;
    u16 auddat = 0, buffer = 0, state = 0b101;
    bool intreq2 = false, audDR = false;
    explicit StateMachine(Paula &p) : paula(p) {}
    bool AUDxON() const { return true; }
    void AUDxIR() const {}
    void AUDxDR() { audDR = true; }
    void volcntrld() { audvol = audvolLatch; }
    bool napnav() const { return !AUDxAP() || AUDxAV(); }
    // DAC output is not an observation of this register/request probe.
    void penhi() {}
    void penlo() {}
    bool AUDxAV() const;
    bool AUDxAP() const;
    void pokeAUDxPER(u16 value);
    void pokeAUDxVOL(u16 value);
    void percntrld();
    void pbufld1();
    void pbufld2();
    void move_101_010();
    void move_010_011();
    void move_011_010();
};
struct Paula {
    u16 adkcon = 0;
    StateMachine<0> channel0{*this};
    StateMachine<1> channel1{*this};
    StateMachine<2> channel2{*this};
    StateMachine<3> channel3{*this};
};
"""
main = r"""
constexpr u16 words[] = {0x0011, 0x0122, 0x0233, 0x0344, 0x0400, 0x0501, 0x067f, 0x0720};
template<isize nr> void run(unsigned mode, unsigned period, unsigned grant_interval) {
    Paula p;
    auto &ch = [&]() -> StateMachine<nr>& {
        if constexpr(nr == 0) return p.channel0;
        if constexpr(nr == 1) return p.channel1;
        if constexpr(nr == 2) return p.channel2;
        if constexpr(nr == 3) return p.channel3;
    }();
    p.adkcon = ((mode & 1) ? 0x10 : 0) << nr;
    p.adkcon |= ((mode & 2) ? 0x01 : 0) << nr;
    ch.pokeAUDxPER(period);
    ch.auddat = words[0];
    ch.move_101_010();
    unsigned delivered = 1;
    for (unsigned t = 0; t <= 6 * period; ++t) {
        if(t) {
            ch.agnus.now = 8ULL * t;
            // Service an outstanding request only on the configured grant cadence.
            // No native/reference request is synthesized by this adapter.
            if(ch.audDR && t % grant_interval == 0) {
                ch.audDR = false;
                ch.auddat = words[delivered++ % 8];
            }
            if(ch.agnus.now == ch.agnus.due) {
                if(ch.state == 0b010) ch.move_010_011();
                else { assert(ch.state == 0b011); ch.move_011_010(); }
            }
        }
        if(t == 0 || t % period == 0 || t % period == 1 || t % period == period - 1) {
            std::cout << nr << ',' << mode << ',' << period << ',' << grant_interval << ',' << t << ',' << delivered << ',' << ch.audDR << ',' << ch.audDR;
            std::cout << ',' << p.channel0.audperLatch << ',' << p.channel0.audvolLatch;
            std::cout << ',' << p.channel1.audperLatch << ',' << p.channel1.audvolLatch;
            std::cout << ',' << p.channel2.audperLatch << ',' << p.channel2.audvolLatch;
            std::cout << ',' << p.channel3.audperLatch << ',' << p.channel3.audvolLatch << '\n';
        }
    }
}
int main() {
    for(unsigned mode : {0,1,2,3}) for(unsigned period : {1,8,124}) for(unsigned interval : {1,5}) {
        run<0>(mode,period,interval); run<1>(mode,period,interval); run<2>(mode,period,interval); run<3>(mode,period,interval);
    }
}
"""
source = prefix
for name in ["pokeAUDxPER", "pokeAUDxVOL"]:
    source += extract(regs, name) + "\n"
for name in [
    "percntrld",
    "pbufld1",
    "pbufld2",
    "move_101_010",
    "move_010_011",
    "move_011_010",
]:
    source += extract(state, name) + "\n"
for name in ["AUDxAV", "AUDxAP"]:
    source += extract(state, name, "bool") + "\n"
source += main
(out / "reference.cpp").write_text(source)
(out / "reference.cpp.gz").write_bytes(gzip.compress(source.encode(), mtime=0))
subprocess.run(
    [
        "c++",
        "-std=c++20",
        "-Wall",
        "-Wextra",
        "-Werror",
        str(out / "reference.cpp"),
        "-o",
        str(out / "reference"),
    ],
    check=True,
)
result = subprocess.check_output([str(out / "reference")], text=True)
(out / "reference.csv").write_text(result)
(out / "source-hashes.json").write_text(
    json.dumps(
        {
            str(p.relative_to(root)): hashlib.sha256(p.read_bytes()).hexdigest()
            for p in [state, regs, header]
        },
        indent=2,
    )
    + "\n"
)
print(f"Executed {len(result.splitlines())} observations from 96 scenarios")
