[package]
name = "ferranti-ula-6c001e"
description = "Ferranti 6C001E ULA for the ZX Spectrum 48K"
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
common-sinclair-zx-spectrum = { path = "../common-sinclair-zx-spectrum", version = "0.15.0" }
serde = { workspace = true }

[lints]
workspace = true
