[package]
name = "common-sinclair-zx-spectrum-amstrad-class"
description = "Shared composition for Amstrad-built Spectrum variants (+2A, +2B, +3)"
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
amstrad-ula-40077 = { path = "../amstrad-ula-40077", version = "0.6.0" }
common-sinclair-zx-spectrum = { path = "../common-sinclair-zx-spectrum", version = "0.6.0" }
gi-ay-3-8912 = { path = "../gi-ay-3-8912", version = "0.6.0" }
nec-upd765a = { path = "../nec-upd765a", version = "0.6.0" }
serde = { workspace = true }
zilog-z80 = { path = "../zilog-z80", version = "0.6.0" }

[lints]
workspace = true

[dev-dependencies]
serde_json = { workspace = true }
