"""Execute vAmiga audio interrupt/manual transitions with explicit scheduled IRQ delivery."""

import argparse
import gzip
import hashlib
import json
import subprocess
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--source", type=Path, required=True)
parser.add_argument("--output", type=Path, required=True)
args = parser.parse_args()
root = args.source.resolve()
out = args.output.resolve()
out.mkdir(parents=True, exist_ok=True)
revision = subprocess.check_output(
    ["git", "rev-parse", "HEAD"], cwd=root, text=True
).strip()
if revision != "60fd1e6b69dcd77c9f44d1291bd37ec715362ab0":
    raise ValueError(f"unregistered vAmiga revision: {revision}")


def extract(path: Path, name: str, result: str = "void") -> str:
    source = path.read_text()
    start = source.index(f"template <isize nr> {result}\nStateMachine<nr>::{name}(")
    brace = source.index("{", start)
    depth, end = 1, brace + 1
    while depth:
        depth += (source[end] == "{") - (source[end] == "}")
        end += 1
    return source[start:end]


state = root / "Core/Components/Paula/Audio/StateMachine.cpp"
regs = root / "Core/Components/Paula/Audio/StateMachineRegs.cpp"
header = root / "Core/Components/Paula/Audio/StateMachine.h"
prefix = r"""
// SPDX-License-Identifier: GPL-3.0-only
// Extracted vAmiga methods: Copyright (C) Dirk W. Hoffmann.
// Scheduler and deterministic external input adapter generated by reference.py.
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <cstdlib>
#include <iostream>
#include <limits>
using isize = long; using u16 = uint16_t; using u64 = uint64_t;
using i8 = int8_t; using i16 = int16_t; using EventSlot = int;
constexpr u64 NEVER = std::numeric_limits<u64>::max();
#define logdebug(...)
#define DMA_CYCLES(n) (8ULL * (n))
#define GET_BIT(n,b) (((n) >> (b)) & 1)
#define HI_BYTE(n) ((n) >> 8)
#define LO_BYTE(n) ((n) & 255)
#define fatalError std::abort()
namespace debug { constexpr bool DISABLE_AUDIRQ = false; }
enum { SLOT_CH0, SLOT_CH1, SLOT_CH2, SLOT_CH3, CHX_PERFIN };
enum class IrqSource { AUD0=7, AUD1=8, AUD2=9, AUD3=10 };
struct ClockRecorder {
    u64 clock = 0, due = NEVER;
    int id[4] = {CHX_PERFIN, CHX_PERFIN, CHX_PERFIN, CHX_PERFIN};
    template<int slot> void scheduleRel(u64 delay, int) { due = clock + delay; }
    template<int slot> void cancel() { due = NEVER; }
};
struct Sampler {
    i16 last = 0;
    bool isFull() const { return false; }
    void append(u64, i16 value) { last = value; }
};
struct AudioPort { Sampler sampler[4]; };
struct AmigaStub { int objid = 0; };
struct Paula;
template<isize nr> struct StateMachine {
    Paula &paula;
    ClockRecorder agnus;
    AudioPort audioPort;
    AmigaStub amiga;
    u16 audperLatch=8, audvolLatch=64, audvol=64;
    u16 auddat=0, buffer=0, state=0, audlen=1, audlenLatch=1;
    bool dma=false, intreq2=false, audDR=false, enablePenlo=false, enablePenhi=false;
    explicit StateMachine(Paula &p): paula(p) {}
    bool AUDxON() const { return dma; }
    bool AUDxIP() const;
    void AUDxIR() const;
    void AUDxDR() { audDR = true; }
    void AUDxDSR() {}
    void lencntrld() { audlen = audlenLatch; }
    void lencount() { --audlen; }
    bool lenfin() { return audlen == 1; }
    void volcntrld() { audvol = audvolLatch; }
    bool napnav() const { return !AUDxAP() || AUDxAV(); }
    void penhi(); void penlo();
    bool AUDxAV() const; bool AUDxAP() const;
    void pokeAUDxPER(u16 value); void pokeAUDxVOL(u16 value); void pokeAUDxDAT(u16 value);
    void percntrld(); void pbufld1(); void pbufld2();
    void move_000_010(); void move_000_001(); void move_001_101();
    void move_101_010(); void move_010_011(); void move_011_010(); void move_011_000();
    void serviceEvent();
};
struct Paula {
    u16 adkcon=0, intreq=0;
    u64 clock=0, irq_due[16];
    StateMachine<0> channel0{*this}; StateMachine<1> channel1{*this};
    StateMachine<2> channel2{*this}; StateMachine<3> channel3{*this};
    Paula() { for(auto &due : irq_due) due=NEVER; }
    // Record the actual AUDxIR requested deadline. Like scheduleIrqAbs,
    // repeated requests keep the earliest outstanding deadline.
    void scheduleIrqRel(IrqSource source, u64 delay) {
        auto &due=irq_due[static_cast<unsigned>(source)];
        due=std::min(due,clock+delay);
    }
    void deliver_irqs() {
        for(unsigned i=0;i<16;++i) if(clock>=irq_due[i]) {
            intreq|=1<<i; irq_due[i]=NEVER;
        }
    }
};
"""
main = r"""
template<isize nr> StateMachine<nr>& channel(Paula &p) {
    if constexpr(nr==0) return p.channel0;
    if constexpr(nr==1) return p.channel1;
    if constexpr(nr==2) return p.channel2;
    if constexpr(nr==3) return p.channel3;
}
template<isize nr> void dma_case(unsigned mode, unsigned arrival) {
    Paula p; auto &ch=channel<nr>(p);
    ch.dma=true; ch.state=0b101; ch.audperLatch=16;
    p.adkcon=(((mode&1)?0x10:0)|((mode&2)?1:0))<<nr;
    ch.pokeAUDxDAT(0x1122);
    bool delivered=false;
    for(unsigned t=0;t<=50;++t) {
        if(t) {
            p.clock=ch.agnus.clock=t*8;
            p.deliver_irqs();
            if(!delivered && t>=arrival && ch.audDR) {
                ch.audDR=false; ch.pokeAUDxDAT(0x3344); delivered=true;
            }
            if(ch.agnus.due==ch.agnus.clock) ch.serviceEvent();
        }
        std::cout<<"dma,"<<nr<<','<<mode<<','<<arrival<<','<<t<<','
                 <<((p.intreq>>(7+nr))&1)<<','<<delivered<<'\n';
    }
}
template<isize nr> void manual_case(unsigned scenario) {
    Paula p; auto &ch=channel<nr>(p);
    if(scenario==1) p.intreq|=1<<(7+nr);
    ch.pokeAUDxDAT(0x1122);
    for(unsigned t=0;t<=23;++t) {
        if(t) {
            p.clock=ch.agnus.clock=t*8;
            p.deliver_irqs();
            if((scenario==2 || scenario==3) && t==7) p.intreq&=~(1<<(7+nr));
            if(scenario==4 && t==17) p.intreq&=~(1<<(7+nr));
            if((scenario==2 && t==12)||(scenario==3 && t==4)||(scenario==4 && t==20)) ch.pokeAUDxDAT(0x3344);
            if(ch.agnus.due==ch.agnus.clock) ch.serviceEvent();
        }
        std::cout<<"manual,"<<nr<<','<<scenario<<",0,"<<t<<','
                 <<((p.intreq>>(7+nr))&1)<<','<<ch.audioPort.sampler[nr].last/64<<'\n';
    }
}
int main() {
    for(unsigned mode:{0,1,2,3}) for(unsigned arrival:{1,7,15,17,23,31}) {
        dma_case<0>(mode,arrival); dma_case<1>(mode,arrival);
        dma_case<2>(mode,arrival); dma_case<3>(mode,arrival);
    }
    for(unsigned scenario:{0,1,2,3,4}) {
        manual_case<0>(scenario); manual_case<1>(scenario);
        manual_case<2>(scenario); manual_case<3>(scenario);
    }
}
"""

events = root / "Core/Components/Paula/Audio/StateMachineEvents.cpp"
source = prefix
for name in ["pokeAUDxPER", "pokeAUDxVOL", "pokeAUDxDAT"]:
    source += extract(regs, name) + "\n"
for name in [
    "AUDxIR",
    "percntrld",
    "pbufld1",
    "pbufld2",
    "penhi",
    "penlo",
    "move_000_010",
    "move_000_001",
    "move_001_101",
    "move_101_010",
    "move_010_011",
    "move_011_010",
    "move_011_000",
]:
    source += extract(state, name) + "\n"
for name in ["AUDxAV", "AUDxAP", "AUDxIP"]:
    source += extract(state, name, "bool") + "\n"
source += extract(events, "serviceEvent") + "\n" + main
(out / "reference.cpp").write_text(source)
(out / "reference.cpp.gz").write_bytes(gzip.compress(source.encode(), mtime=0))
subprocess.run(
    [
        "c++",
        "-std=c++20",
        "-Wall",
        "-Wextra",
        "-Werror",
        str(out / "reference.cpp"),
        "-o",
        str(out / "reference"),
    ],
    check=True,
)
result = subprocess.check_output([str(out / "reference")], text=True)
(out / "reference.csv").write_text(result)
(out / "source-hashes.json").write_text(
    json.dumps(
        {
            str(p.relative_to(root)): hashlib.sha256(p.read_bytes()).hexdigest()
            for p in [state, regs, header, events]
        },
        indent=2,
    )
    + "\n"
)
print(f"Executed {len(result.splitlines())} observations across 116 scenarios")
