[package]
name = "format-dragon-cas"
description = "Dragon 32 CAS cassette image parsing"
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
