//! Fixture-free proof that the machine starts.
//!
//! The ZX80 needs its manufacturer's ROM to reach a prompt, and that ROM
//! cannot be copied to a public runner — and unlike the Spectrum it is not
//! covered by Amstrad's permission, which stops at the machines Amstrad
//! actually bought. Its rights sit with Nine Tiles. So synthetic firmware is
//! not merely the cheap route here, it is the only one available.
//!
//! ## What a pass proves, stated carefully
//!
//! On real hardware the **CPU** generates the picture: the Z80 executes
//! through the display file while the discrete logic forces NOPs and turns
//! the fetched bytes into video. Since #1033 this machine models exactly
//! that — and the consequence is that this image cannot produce a picture.
//! It writes a display file and spins; it never executes one. A ZX80 that
//! is not running its display routine shows a blank screen, which is the
//! machine's defining behaviour and not a failure.
//!
//! So a pass here proves the CPU executed from reset, set `I`, and wrote
//! the display file it was asked to write. Evidence that display generation
//! works is a different test with a different subject: `rom_boot` runs the
//! manufacturer's ROM and asserts the cursor lands as a single 8x8 cell.
//!
//! Before #1033 this file asserted a screenful of ink, because the machine
//! borrowed the ZX81's ULA and rendered the display file from the `D_FILE`
//! pointer once a frame. That assertion passed for a machine with no
//! display generation at all, which is what made it worth replacing.
//!
//! ## The firmware has to point `I` at a character set
//!
//! Character bitmaps live at `I << 8 | char << 3 | line`, as on hardware, so
//! nothing legible appears until the firmware sets `I`. This image sets it to
//! the page the real ROM uses, and the ROM is zero-filled there — so glyph 0
//! is blank, and the display file is written with `$80`: glyph 0 *inverted*,
//! solid only because inverting a blank bitmap sets every pixel.
//!
//! That makes the test depend on two separate things the firmware must do —
//! setting `I` and writing the display file — and on neither being true by
//! accident. A glyph already solid in ROM would light the screen with the CPU
//! switched off, which is the trap the PET's character ROM avoids the same
//! way.
//!
//! Before #1030 the character address was hardcoded to `$0000` and this image
//! was built around that. It no longer needs the trick, and now exercises `I`
//! instead.
//!
//! The image is generated by
//! `test-data/synthetic-firmware/build-synthetic-firmware.py`.

use std::path::PathBuf;

use machine_sinclair_zx80::Zx80;

/// Ink.
const INK: u32 = 0xFF00_0000;

fn firmware(name: &str) -> Vec<u8> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../test-data/synthetic-firmware")
        .join(name);
    std::fs::read(path).expect("firmware image")
}

fn booted(name: &str) -> Zx80 {
    let mut machine = Zx80::new(firmware(name), 16 * 1024).expect("synthetic ROM should init");
    for _ in 0..20 {
        machine.run_frame();
    }
    machine
}

#[test]
fn synthetic_firmware_runs_and_writes_its_display_file() {
    let machine = booted("sinclair-zx80.rom");

    assert_eq!(
        machine.cpu().regs.i,
        0x0E,
        "the firmware should point I at the character set page"
    );

    // The display file it was asked to write: 24 rows of 32 solid glyphs,
    // each row closed by a NEWLINE. Reading it back proves the CPU ran the
    // fill loop to completion, which a stalled or crashed machine cannot.
    let row_start = 0x4101;
    let glyphs = (0..32)
        .filter(|i| machine.peek_memory(row_start + i) == 0x80)
        .count();
    assert_eq!(glyphs, 32, "the first row should be 32 solid glyphs");
    assert_eq!(
        machine.peek_memory(row_start + 32),
        0x76,
        "and closed by a NEWLINE"
    );
    let last_row = 0x4101 + 23 * 33;
    assert_eq!(
        machine.peek_memory(last_row),
        0x80,
        "the fill should have reached the 24th row, not stopped early"
    );

    // And the screen stays blank, because nothing executed that display
    // file. This is the assertion that would have failed before #1033.
    let ink = machine
        .framebuffer()
        .iter()
        .filter(|&&pixel| pixel == INK)
        .count();
    assert_eq!(
        ink, 0,
        "a ZX80 shows a picture only while the CPU is executing forced NOPs \
         from the display file; this firmware never does, so the screen is \
         blank. {ink} ink pixels means something is rendering the display \
         file behind the CPU's back"
    );
}

/// The control image spins without writing a display file at all, so the
/// bytes the other test reads back stay zero. It separates "the CPU ran the
/// firmware" from "the RAM happened to contain this", which matters when
/// the rendering assertion is an absence.
#[test]
fn the_control_image_writes_no_display_file() {
    let machine = booted("sinclair-zx80-control.rom");
    assert_eq!(machine.cpu().regs.i, 0x00, "the control image sets no I");
    let written = (0..32)
        .filter(|i| machine.peek_memory(0x4101 + i) == 0x80)
        .count();
    assert_eq!(written, 0, "and writes no display file");
}
