//! Fixture-free proof that the machine starts.
//!
//! The ZX80 needs its manufacturer's ROM to reach a prompt, and that ROM
//! cannot be copied to a public runner — and unlike the Spectrum it is not
//! covered by Amstrad's permission, which stops at the machines Amstrad
//! actually bought. Its rights sit with Nine Tiles. So synthetic firmware is
//! not merely the cheap route here, it is the only one available.
//!
//! ## What a pass proves, stated carefully
//!
//! On real hardware the **CPU** generates the picture: it executes through
//! the display file while the discrete logic forces NOPs and turns the
//! fetched bytes into video. Since #1033 this machine models exactly that,
//! and since #1037 this image drives it — the firmware runs a display
//! routine of its own, with an interrupt handler that counts scanlines and
//! jumps back into the display file, as Sinclair's ROM does.
//!
//! So a pass proves the whole path: the CPU executed from reset, set `I`,
//! wrote a display file, and then *generated a picture out of it* — the
//! forced NOPs, the character latch, the address composed during `/REFRESH`,
//! and the line timing off A6 of the refresh counter. On a runner with no
//! ROM, this is the only evidence of that; `rom_boot` proves more but needs
//! firmware that cannot be copied to a public machine.
//!
//! Between #1033 and #1037 this file asserted the screen stayed **blank**,
//! which was correct for an image that wrote a display file and never
//! executed one, but left CI with no rendering evidence at all. Before
//! #1033 it asserted a screenful of ink and passed for a machine that
//! borrowed the ZX81's ULA and had no display generation whatsoever. Both
//! are worth remembering when this file's assertions get weakened again.
//!
//! ## The firmware has to point `I` at a character set
//!
//! Character bitmaps live at `I << 8 | char << 3 | line`, as on hardware, so
//! nothing legible appears until the firmware sets `I`. This image sets it to
//! the page the real ROM uses, and the ROM is zero-filled there — so glyph 0
//! is blank, and the display file is written with `$80`: glyph 0 *inverted*,
//! solid only because inverting a blank bitmap sets every pixel.
//!
//! That makes the test depend on two separate things the firmware must do —
//! setting `I` and writing the display file — and on neither being true by
//! accident. A glyph already solid in ROM would light the screen with the CPU
//! switched off, which is the trap the PET's character ROM avoids the same
//! way.
//!
//! Before #1030 the character address was hardcoded to `$0000` and this image
//! was built around that. It no longer needs the trick, and now exercises `I`
//! instead.
//!
//! The image is generated by
//! `test-data/synthetic-firmware/build-synthetic-firmware.py`.

use std::path::PathBuf;

use machine_sinclair_zx80::{FB_WIDTH, Zx80};

/// Ink.
const INK: u32 = 0xFF00_0000;

fn firmware(name: &str) -> Vec<u8> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../test-data/synthetic-firmware")
        .join(name);
    std::fs::read(path).expect("firmware image")
}

fn booted(name: &str) -> Zx80 {
    let mut machine = Zx80::new(firmware(name), 16 * 1024).expect("synthetic ROM should init");
    for _ in 0..20 {
        machine.run_frame();
    }
    machine
}

#[test]
fn synthetic_firmware_generates_a_picture_with_the_cpu() {
    let machine = booted("sinclair-zx80.rom");

    assert_eq!(
        machine.cpu().regs.i,
        0x0E,
        "the firmware should point I at the character set page"
    );

    // 24 rows of 32 glyphs, every pixel set: the display area is 256x192,
    // starting 32 rows down and 32 pixels in, inside a 320x288 window.
    let frame = machine.framebuffer();
    let ink = frame.iter().filter(|&&pixel| pixel == INK).count();
    assert_eq!(
        ink,
        256 * 192,
        "the display area should be solid ink; got {ink} of {} pixels",
        frame.len()
    );

    // Where the ink is matters as much as how much. A renderer that drew the
    // display file straight from memory would fill the same area; one that
    // generates it with the CPU has to get the horizontal timing right, and
    // a routine that dawdles between the interrupt and the first character
    // fetch pushes every line to the right.
    let w = FB_WIDTH as usize;
    // The display starts at frame line 56 and a set blanks the first 24, so it
    // occupies rows 32..=223 of the 288-line window: first row, second, the
    // last of the first character row, the middle, and the last row.
    for row in [32usize, 33, 39, 128, 223] {
        let lit: Vec<usize> = (0..w).filter(|&x| frame[row * w + x] == INK).collect();
        assert_eq!(
            (lit.first().copied(), lit.last().copied(), lit.len()),
            (Some(32), Some(287), 256),
            "row {row} should be 32 characters starting at x=32"
        );
    }
    // Border: the top of the window, the last row above the display, the
    // first below it, and the bottom. Sixty-four lines below against
    // thirty-two above is the ROM's own split, not a symmetric crop.
    for row in [0usize, 31, 224, 287] {
        let lit = (0..w).filter(|&x| frame[row * w + x] == INK).count();
        assert_eq!(lit, 0, "row {row} is border and must stay blank");
    }
}

/// The control image spins without writing a display file and without
/// running a display routine, so it renders nothing — which is also what a
/// ZX80 does whenever it is busy. It separates "the CPU generated this
/// picture" from "something drew the display file behind the CPU's back":
/// a renderer that walked `D_FILE` once a frame would light this one up too.
#[test]
fn the_control_image_generates_no_picture() {
    let machine = booted("sinclair-zx80-control.rom");
    let ink = machine
        .framebuffer()
        .iter()
        .filter(|&&pixel| pixel == INK)
        .count();
    assert_eq!(
        ink, 0,
        "a machine running no display routine shows nothing; got {ink} ink pixels"
    );
}

/// The window has to be a set's window, not a snug fit round the picture.
///
/// The ZX80's vertical position is software-timed: the firmware counts border
/// lines and then jumps into the display file, so a routine that counts
/// differently puts the picture somewhere else. A real set shows 288 lines and
/// the picture moves within them. A 240-line window clipped that movement,
/// which is #1054.
///
/// This drives it directly by rewriting the firmware's border count — the
/// `ld c,BORDER_LINES` immediate — and checking the picture both moved and
/// survived whole. Under the old window the later of these two would have
/// lost rows off the bottom.
#[test]
fn a_software_moved_picture_stays_whole() {
    /// `ld c,n` — the instruction that loads the border-line count.
    const LD_C: u8 = 0x0E;
    /// The value `BORDER_LINES` assembles to.
    const DEFAULT_BORDER_LINES: u8 = 47;

    let base = firmware("sinclair-zx80.rom");
    let sites: Vec<usize> = base
        .windows(2)
        .enumerate()
        .filter(|(_, w)| w[0] == LD_C && w[1] == DEFAULT_BORDER_LINES)
        .map(|(at, _)| at)
        .collect();
    assert_eq!(
        sites.len(),
        1,
        "expected one `ld c,{DEFAULT_BORDER_LINES}` to rewrite, found {}",
        sites.len()
    );
    let operand = sites[0] + 1;

    let top_row = |border_lines: u8| -> usize {
        let mut rom = base.clone();
        rom[operand] = border_lines;
        let mut machine = Zx80::new(rom, 16 * 1024).expect("synthetic ROM should init");
        for _ in 0..20 {
            machine.run_frame();
        }
        let frame = machine.framebuffer();
        let ink = frame.iter().filter(|&&pixel| pixel == INK).count();
        assert_eq!(
            ink,
            256 * 192,
            "the picture should survive whole at {border_lines} border lines; \
             got {ink} of {} pixels, so it clipped",
            frame.len()
        );
        frame
            .chunks(FB_WIDTH as usize)
            .position(|row| row.contains(&INK))
            .expect("the picture should be somewhere")
    };

    // The moves are sized to the window, not chosen for roundness. The old
    // 240-line window left 24 lines of border above the picture and 24 below,
    // so a 24-line move up is exactly what it could still hold and a 40-line
    // move down is not — that asymmetry is what makes this a regression test
    // rather than a description. Both fit the 288-line window with room over.
    let earlier = top_row(DEFAULT_BORDER_LINES - 24);
    let default = top_row(DEFAULT_BORDER_LINES);
    let later = top_row(DEFAULT_BORDER_LINES + 40);

    assert!(
        earlier < default && default < later,
        "counting more border lines should push the picture down: \
         {earlier}, {default}, {later}"
    );
    assert_eq!(
        (default - earlier, later - default),
        (24, 40),
        "a line of border should move the picture exactly one line"
    );
}
