//! Fixture-free proof that the machine starts.
//!
//! The BBC Micro needs its manufacturer's ROM to reach a prompt, and that ROM
//! cannot be copied to a public runner. So this asks the weaker question CI
//! *can* answer: put code this project wrote in the ROM socket, and see
//! whether the machine runs it.
//!
//! It does **not** prove the real firmware boots.
//!
//! Unlike every other synthetic-firmware machine here, **there is no display
//! at all until the firmware makes one.** The 6845's registers are zero at
//! reset, so the program has to build a raster before it can colour it. That
//! makes this the strongest of the synthetic proofs: a pass means the CPU
//! executed roughly fifty instructions of setup in the right order, the
//! CRTC took every register write, the Video ULA took its control and palette writes, and a frame came out.
//!
//! The image is generated by
//! `test-data/synthetic-firmware/build-synthetic-firmware.py`.
//!
//! The screen is never filled. All sixteen logical colours are mapped to one
//! physical colour instead, so whatever uninitialised screen RAM holds, the
//! display comes out uniform. That keeps the test about the video path
//! rather than about what RAM happened to contain.

use std::path::PathBuf;

use machine_acorn_bbc_micro::BbcMicro;

/// What every logical colour mapped to physical 1 renders.
const PALETTE: u32 = 0xFFFF_0000;

fn firmware(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../test-data/synthetic-firmware")
        .join(name)
}

fn booted(name: &str) -> BbcMicro {
    let rom = std::fs::read(firmware(name)).expect("firmware image");
    let mut machine = BbcMicro::new(rom);
    for _ in 0..20 {
        machine.run_frame();
    }
    machine
}

#[test]
fn synthetic_firmware_builds_a_raster_and_floods_it() {
    let machine = booted("acorn-bbc-micro.rom");
    assert!(
        machine.framebuffer().iter().all(|&pixel| pixel == PALETTE),
        "every logical colour maps to one physical colour, so the frame is uniform"
    );
}

/// The control image spins without programming the CRTC.
#[test]
fn the_control_image_renders_no_raster() {
    let machine = booted("acorn-bbc-micro-control.rom");
    assert_eq!(
        machine
            .framebuffer()
            .iter()
            .filter(|&&p| p == PALETTE)
            .count(),
        0,
        "a machine that never programmed its CRTC cannot show a raster"
    );
}
