//! ZX Spectrum BASIC keyword-to-token mapping.
//!
//! Token values $A5–$FF. Sorted longest-first so the tokeniser
//! performs greedy matching (e.g. "GO TO" before "GO").

/// `(keyword_text, token_byte)` — sorted by keyword length descending.
pub const KEYWORDS: &[(&str, u8)] = &[
    // 10+ characters
    ("RANDOMIZE ", 0xF9),
    ("CONTINUE ", 0xE8),
    ("RESTORE ", 0xE5),
    ("INVERSE ", 0xDD),
    ("BRIGHT ", 0xDC),
    ("VERIFY ", 0xD6),
    ("CIRCLE ", 0xD8),
    ("BORDER ", 0xE7),
    ("RETURN ", 0xFE),
    ("LPRINT ", 0xE0),
    ("SCREEN$ ", 0xAA),
    ("INKEY$ ", 0xA6),
    ("FORMAT ", 0xD0),
    ("MERGE ", 0xD5),
    ("ERASE ", 0xD2),
    ("CLOSE #", 0xD4),
    ("OPEN #", 0xD3),
    ("PRINT ", 0xF5),
    ("INPUT ", 0xEE),
    ("PAUSE ", 0xF2),
    ("CLEAR ", 0xFD),
    ("FLASH ", 0xDB),
    ("PAPER ", 0xDA),
    ("POINT ", 0xA9),
    ("LLIST ", 0xE1),
    ("GO SUB ", 0xED),
    ("GO TO ", 0xEC),
    ("DEF FN ", 0xCE),
    ("DRAW ", 0xFC),
    ("PLOT ", 0xF6),
    ("POKE ", 0xF4),
    ("NEXT ", 0xF3),
    ("READ ", 0xE3),
    ("DATA ", 0xE4),
    ("SAVE ", 0xF8),
    ("LOAD ", 0xEF),
    ("LIST ", 0xF0),
    ("STOP ", 0xE2),
    ("BEEP ", 0xD7),
    ("MOVE ", 0xD1),
    ("COPY", 0xFF),
    ("OVER ", 0xDE),
    ("ATTR ", 0xAB),
    ("VAL$ ", 0xAE),
    ("STR$ ", 0xC1),
    ("CHR$ ", 0xC2),
    ("STEP ", 0xCD),
    ("THEN ", 0xCB),
    ("LINE ", 0xCA),
    ("PEEK ", 0xBE),
    ("CODE ", 0xAF),
    ("DIM ", 0xE9),
    ("REM ", 0xEA),
    ("FOR ", 0xEB),
    ("RUN ", 0xF7),
    ("CLS", 0xFB),
    ("LET ", 0xF1),
    ("NEW", 0xE6),
    ("OUT ", 0xDF),
    ("INK ", 0xD9),
    ("CAT ", 0xCF),
    ("NOT ", 0xC3),
    ("BIN ", 0xC4),
    ("AND ", 0xC6),
    ("VAL ", 0xB0),
    ("LEN ", 0xB1),
    ("SIN ", 0xB2),
    ("COS ", 0xB3),
    ("TAN ", 0xB4),
    ("ASN ", 0xB5),
    ("ACS ", 0xB6),
    ("ATN ", 0xB7),
    ("EXP ", 0xB9),
    ("INT ", 0xBA),
    ("SQR ", 0xBB),
    ("SGN ", 0xBC),
    ("ABS ", 0xBD),
    ("USR ", 0xC0),
    ("IF ", 0xFA),
    ("OR ", 0xC5),
    ("AT ", 0xAC),
    ("TO ", 0xCC),
    ("IN ", 0xBF),
    ("LN ", 0xB8),
    ("FN ", 0xA8),
    ("TAB ", 0xAD),
    ("PI", 0xA7),
    ("RND", 0xA5),
    ("<>", 0xC9),
    ("<=", 0xC7),
    (">=", 0xC8),
];
