[package]
name = "format-dragon-disk"
description = "DragonDOS VDK disk image parsing"
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
