[package]
name = "machine-sord-m5"
description = "Sord M5 machine wiring — Z80 + TMS9918A + SN76489A"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ti-sn76489 = { path = "../ti-sn76489", version = "0.17.0" }
ti-tms9918 = { path = "../ti-tms9918", version = "0.17.0" }
emu198x-zilog-z80 = { path = "../emu198x-zilog-z80", version = "0.6.0" }
zilog-z80-ctc = { path = "../zilog-z80-ctc", version = "0.17.0" }
serde = { workspace = true }
serde-big-array = { workspace = true }

[dev-dependencies]
postcard = { workspace = true }

[lints]
workspace = true
