//! CRC32s of the Atari 5200 cartridges that use the two-chip layout.
//!
//! Generated by `tools/a5200-cart-layouts.py` from MAME's `a5200.xml`
//! software list (CC0-1.0). Do not edit by hand -- rerun the script.
//!
//! A 16 KB image whose CRC32 appears here is two-chip; every other image is
//! linear. See `knowledge/decisions/cart-layout-needs-positive-evidence.md`.

/// Sorted for `binary_search`.
pub(crate) const TWO_CHIP_16K_CRC32: [u32; 39] = [
    0x0480_7705, // Buck Rogers - Planet of Zoom
    0x04B2_99A4, // Frisky Tom (prototype)
    0x0AF1_9345, // Frogger II: Threeedeep!
    0x0F99_6184, // RealSports Basketball (prototype, 19821105)
    0x10F3_3C90, // RealSports Tennis
    0x1D1C_EE27, // Stargate (prototype)
    0x2A64_0143, // Montezuma's Revenge
    0x2C67_6662, // Jungle Hunt
    0x4019_ECEC, // Astro Chase
    0x4336_C2CC, // RealSports Football
    0x536A_70FE, // Centipede
    0x5998_3C40, // Jr Pacman (prototype)
    0x69F2_3548, // Star Trek
    0x6A68_7F9C, // Dig Dug
    0x73B5_B6FB, // Sport Goofy (prototype)
    0x752F_5EFD, // Ms. Pac-Man
    0x75F5_66DF, // Star Wars - The Arcade Game
    0x7D81_9A9F, // Star Raiders
    0x84DF_4925, // Looney Tunes Hotel (prototype)
    0x8873_EF51, // Pac-Man
    0x931A_454A, // Microgammon SB (prototype)
    0xA18A_9A40, // Popeye
    0xA976_06AB, // Road Runner (prototype)
    0xABC2_D1E4, // Pole Position
    0xAEA6_D2C2, // Qix
    0xB3B8_E314, // Battlezone (prototype)
    0xB68D_61E8, // Space Dungeon
    0xB8FA_AEC3, // Xari Arena (prototype)
    0xBD52_623B, // Defender
    0xBFD3_0C01, // Joust
    0xC597_C087, // Miniature Golf (prototype)
    0xCE07_D9AD, // Atari PAM Diagnostics (rev 2.3)
    0xCFD4_A7F9, // Gyruss
    0xD9AE_4518, // James Bond
    0xE8B1_30C4, // PAM Diag 2.0
    0xECBD_1853, // RealSports Soccer
    0xECFA_624F, // Kangaroo
    0xF1F4_2BBD, // Congo Bongo
    0xFD54_1C80, // Countermeasure
];
