[package]
name = "machine-oric-atmos"
description = "Oric-1 / Atmos machine wiring — 6502 + custom ULA + VIA-6522 + AY-3-8910"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gi-ay-3-8912 = { path = "../gi-ay-3-8912", version = "0.12.0" }
emu198x-mos-6502 = { path = "../emu198x-mos-6502", version = "0.6.0" }
mos-via-6522 = { path = "../mos-via-6522", version = "0.12.0" }
serde = { workspace = true }
serde-big-array = { workspace = true }

[dev-dependencies]
postcard = { workspace = true }

[lints]
workspace = true
