//! Fixture-free proof that the machine starts.
//!
//! The Amiga needs its manufacturer's ROM to reach a prompt, and that ROM
//! cannot be copied to a public runner. So this asks the weaker question CI
//! *can* answer: put code this project wrote in the ROM socket, and see
//! whether the machine runs it.
//!
//! A pass proves the reset vector was fetched, the ROM is readable where the
//! memory map says it is, the CPU executed, Denise took its register write,
//! and a frame reached the framebuffer. It does **not** prove the real
//! firmware boots — that claim belongs to the machines whose own ROMs may be
//! distributed, or which have a free reimplementation.
//!
//! The image is generated by
//! `test-data/synthetic-firmware/build-synthetic-firmware.py`, which also
//! builds a control image that spins without touching the hardware. Every
//! control renders black, which is where the expected colour below comes
//! from — measured against "never ran", not assumed.
//!
//! The Amiga has no free-firmware evidence of the stronger kind, and cannot
//! yet: AROS m68k splits itself across two ROM windows and this emulator maps
//! only one. See issue #1022. This is the evidence available meanwhile.

use std::path::PathBuf;

use machine_commodore_amiga_ocs::AmigaOcs;

const PAL_FRAME_TICKS: u64 = 3_546_895 / 50;

/// What `COLOR00 = $0F00` renders. With DMA off there are no bitplanes, so
/// the background register covers the raster edge to edge.
const RED: u32 = 0xFFFF_0000;

fn firmware() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../test-data/synthetic-firmware/commodore-amiga-kickstart.rom")
}

#[test]
fn synthetic_firmware_runs_and_floods_the_display() {
    let rom = std::fs::read(firmware()).expect("kickstart image");
    let mut amiga = AmigaOcs::with_slow_ram(rom, 512 * 1024);
    for _ in 0..(10 * PAL_FRAME_TICKS) {
        amiga.tick();
    }

    let framebuffer = amiga.denise().framebuffer();
    let red = framebuffer.iter().filter(|&&pixel| pixel == RED).count();

    // 99.7% in practice: the remaining 1536 pixels are the same blanking
    // band a real Kickstart leaves black, so this is not a partial paint.
    assert!(
        red * 100 / framebuffer.len() > 95,
        "Denise should show COLOR00 across the raster; got {red} of {} pixels",
        framebuffer.len()
    );
}

/// The control image spins without writing `COLOR00`.
#[test]
fn the_control_image_renders_no_red_at_all() {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../test-data/synthetic-firmware/commodore-amiga-kickstart-control.rom");
    let rom = std::fs::read(path).expect("control image");
    let mut amiga = AmigaOcs::with_slow_ram(rom, 512 * 1024);
    for _ in 0..(10 * PAL_FRAME_TICKS) {
        amiga.tick();
    }

    assert_eq!(
        amiga
            .denise()
            .framebuffer()
            .iter()
            .filter(|&&p| p == RED)
            .count(),
        0,
        "a machine that ran no firmware must not show the firmware's colour"
    );
}
