[package]
name = "runtime-nintendo-nes"
description = "Fresh-workspace NES family metadata and headless runtime wrapper"
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
emu198x-shell = { path = "../emu198x-shell", version = "0.11.0" }
ricoh-ppu-2c02 = { path = "../ricoh-ppu-2c02", version = "0.11.0" }
format-nintendo-nes-ines = { path = "../format-nintendo-nes-ines", version = "0.11.0" }
machine-nintendo-nes = { path = "../machine-nintendo-nes", version = "0.11.0" }
postcard = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
emu198x-test-skip = { path = "../emu198x-test-skip", version = "0.11.0" }

[lints]
workspace = true
