[package]
name = "pentagon-ula"
description = "Pentagon ULA — Russian Spectrum clone, no contention, 14.336 MHz crystal"
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
common-sinclair-zx-spectrum = { path = "../common-sinclair-zx-spectrum", version = "0.2.0" }

[dev-dependencies]
common-sinclair-zx-spectrum = { path = "../common-sinclair-zx-spectrum", version = "0.2.0" }

[lints]
workspace = true
