[package]
name = "emu198x-script-amiga"
description = "Minimal headless Amiga runner."
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
emu198x-shell = { path = "../emu198x-shell" }
runtime-commodore-amiga = { path = "../runtime-commodore-amiga" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[lints]
workspace = true
