//! Fixture-free proof that the machine starts.
//!
//! The Dragon needs its manufacturer's ROM to reach a prompt, and that ROM
//! cannot be copied to a public runner. So this asks the weaker question CI
//! *can* answer: put code this project wrote in the ROM socket, and see
//! whether the machine runs it.
//!
//! A pass proves the 6809 fetched its reset vector from `$FFFE`, executed,
//! wrote 6144 bytes of display RAM, and the VDG fetched them into a frame.
//! It does **not** prove the real firmware boots.
//!
//! ## Two traps, both of which looked like a broken renderer
//!
//! **The VDG is in a graphics mode at reset, not a text mode.** The SAM
//! display base is `$0000` — real firmware moves it to `$0400` — and the
//! mode PIA1's port B selects needs 6144 bytes, not the 512 a 32x16 text
//! screen would. Filling 512 bytes fills an eighth of the display, which
//! reads exactly like a rendering bug.
//!
//! **The fill needs time.** 6144 iterations outrun ten frames, so a short
//! run leaves the screen part-filled — which also reads like a rendering
//! bug. It completes by about 120 frames; this runs 200.
//!
//! Both were diagnosed by reading memory back rather than by staring at
//! pixel counts: the bytes were provably in RAM before the renderer was
//! suspected.
//!
//! The image is generated by
//! `test-data/synthetic-firmware/build-synthetic-firmware.py`.

use std::path::PathBuf;

use machine_dragon_32::{DRAGON_FRAME_CYCLES, Dragon32, ROM_SIZE};
use motorola_vdg_6847::VdgPalette;

/// Every pixel set, in the graphics mode the VDG powers on in.
const LIT: u32 = 0xFFFF_FFFF;

fn firmware(name: &str) -> Box<[u8; ROM_SIZE]> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../test-data/synthetic-firmware")
        .join(name);
    let bytes = std::fs::read(path).expect("firmware image");
    bytes
        .into_boxed_slice()
        .try_into()
        .expect("the image is exactly 16 KiB")
}

fn booted(name: &str) -> Dragon32 {
    let rom = firmware(name);
    let mut machine = Dragon32::new(&rom);
    let _ = machine.run_cycles(200 * DRAGON_FRAME_CYCLES, 0);
    machine
}

#[test]
fn synthetic_firmware_runs_and_fills_the_display() {
    let machine = booted("dragon-32.rom");
    let frame = machine.render_visible_argb(VdgPalette::default());
    let lit = frame.iter().filter(|&&pixel| pixel == LIT).count();
    // 49,152 in practice — 256x192, exactly the display area. The rest is
    // border, which writing display RAM cannot reach.
    assert!(
        lit > frame.len() / 2,
        "the VDG should fetch the display RAM the firmware wrote; got {lit} of {} pixels",
        frame.len()
    );
}

/// The control image spins without writing display RAM.
#[test]
fn the_control_image_lights_nothing() {
    let machine = booted("dragon-32-control.rom");
    let frame = machine.render_visible_argb(VdgPalette::default());
    assert_eq!(
        frame.iter().filter(|&&pixel| pixel == LIT).count(),
        0,
        "a machine that ran no firmware must not light the display"
    );
}
