#!/usr/bin/env python3
"""Generate the Atari 5200 two-chip cartridge table from MAME's software list.

A headerless 5200 dump carries no cart-type byte, and 16 KB images come in
two incompatible layouts that size alone cannot tell apart:

  * linear      - the image maps straight across `$8000-$BFFF`
  * two-chip    - two 8 KB chips decoded by A15, each mirrored twice

MAME records which is which per title in `hash/a5200.xml`, a CC0-1.0 file
carrying no redistribution burden. This script distils the two-chip titles
into a sorted CRC32 table that `machine-atari-5200` uses as positive
evidence: a 16 KB image whose CRC32 is in the table is two-chip, and
everything else is linear -- the same default MAME applies to a headerless
dump.

Run from the repo root:

    python3 tools/a5200-cart-layouts.py --out crates/machine-atari-5200/src/cart_layouts.rs

The vendored hash file lives in the umbrella tree at
`198x/emulators/multi-system/mame/hash/a5200.xml`; pass `--hash-file` when
running from a worktree that cannot see it.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

SOFTWARE_RE = re.compile(r'<software name="([^"]+)".*?</software>', re.S)
DESCRIPTION_RE = re.compile(r"<description>(.*?)</description>", re.S)
SLOT_RE = re.compile(r'<feature name="slot" value="([^"]+)"')
ROM_RE = re.compile(r'<rom name="[^"]*" size="(\d+)" crc="([0-9a-fA-F]+)"')

TWO_CHIP_SLOT = "a5200_2chips"
TWO_CHIP_SIZE = 16384


def find_hash_file(start: Path) -> Path | None:
    """Walk up from the repo looking for the vendored MAME hash file."""
    relative = Path("emulators/multi-system/mame/hash/a5200.xml")
    for parent in [start, *start.parents]:
        candidate = parent / relative
        if candidate.is_file():
            return candidate
    return None


def parse(xml: str) -> list[tuple[int, str]]:
    """Return (crc32, title) for every two-chip 16 KB cartridge."""
    carts: list[tuple[int, str]] = []
    for match in SOFTWARE_RE.finditer(xml):
        entry = match.group(0)
        slot = SLOT_RE.search(entry)
        if slot is None or slot.group(1) != TWO_CHIP_SLOT:
            continue
        roms = ROM_RE.findall(entry)
        if len(roms) != 1:
            raise SystemExit(
                f"{match.group(1)}: expected one <rom>, found {len(roms)}. "
                "The table keys on the whole image, so a split dump needs "
                "handling before it can be included."
            )
        size, crc = roms[0]
        if int(size) != TWO_CHIP_SIZE:
            raise SystemExit(
                f"{match.group(1)}: {TWO_CHIP_SLOT} entry is {size} bytes, "
                f"not {TWO_CHIP_SIZE}. The layout rule assumes 16 KB."
            )
        title = DESCRIPTION_RE.search(entry)
        carts.append((int(crc, 16), title.group(1).strip() if title else match.group(1)))
    return carts


def render(carts: list[tuple[int, str]], source: Path) -> str:
    seen: dict[int, str] = {}
    for crc, title in carts:
        if crc in seen:
            raise SystemExit(
                f"CRC32 collision between {seen[crc]!r} and {title!r} "
                f"(0x{crc:08X}). The table cannot key on CRC32 alone."
            )
        seen[crc] = title

    rows = "\n".join(
        f"    0x{crc >> 16:04X}_{crc & 0xFFFF:04X}, // {title}"
        for crc, title in sorted(carts)
    )
    return f"""//! CRC32s of the Atari 5200 cartridges that use the two-chip layout.
//!
//! Generated by `tools/a5200-cart-layouts.py` from MAME's `{source.name}`
//! software list (CC0-1.0). Do not edit by hand -- rerun the script.
//!
//! A 16 KB image whose CRC32 appears here is two-chip; every other image is
//! linear. See `knowledge/decisions/cart-layout-needs-positive-evidence.md`.

/// Sorted for `binary_search`.
pub(crate) const TWO_CHIP_16K_CRC32: [u32; {len(carts)}] = [
{rows}
];
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--hash-file", type=Path, help="path to MAME's a5200.xml")
    parser.add_argument("--out", type=Path, help="write here instead of stdout")
    args = parser.parse_args()

    hash_file = args.hash_file or find_hash_file(Path.cwd().resolve())
    if hash_file is None:
        parser.error(
            "could not find emulators/multi-system/mame/hash/a5200.xml above "
            f"{Path.cwd()}; pass --hash-file"
        )
    if not hash_file.is_file():
        parser.error(f"{hash_file} is not a file")

    carts = parse(hash_file.read_text(encoding="utf-8", errors="replace"))
    if not carts:
        raise SystemExit(f"no {TWO_CHIP_SLOT} entries in {hash_file}")

    rendered = render(carts, hash_file)
    if args.out:
        args.out.write_text(rendered, encoding="utf-8")
        print(f"{len(carts)} two-chip cartridges -> {args.out}", file=sys.stderr)
    else:
        sys.stdout.write(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
