#!/usr/bin/env python3
"""Generate the Atari 8-bit OSS cartridge table from MAME's software list.

A headerless OSS dump carries no cartridge-type id, and the four OSS banking
boards share their sizes with plain cartridges:

  * M091 one-chip, 043M two-chip and the obsolete 034M image order: 16 KB,
    the same size as a flat 16 KB cartridge at `$8000-$BFFF`
  * OSS 8 KB (The Writer's Tool): 8 KB, the same size as a flat 8 KB
    cartridge at `$A000-$BFFF`

MAME records the board per title in `hash/a800.xml`, a CC0-1.0 file carrying
no redistribution burden. This script distils the OSS titles into a sorted
CRC32 table that `machine-atari-800xl` uses as positive evidence: a
headerless image whose CRC32 is in the table gets that board, and every other
image keeps the plain layout its size implies. See
`knowledge/decisions/cart-layout-needs-positive-evidence.md`.

Run from the repo root:

    python3 tools/a800-oss-cart-types.py --out crates/machine-atari-800xl/src/oss_carts.rs

The vendored hash file lives in the umbrella tree at
`198x/emulators/multi-system/mame/hash/a800.xml`; pass `--hash-file` when
running from a worktree that cannot see it.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

SOFTWARE_RE = re.compile(r'<software name="([^"]+)".*?</software>', re.S)
DESCRIPTION_RE = re.compile(r"<description>(.*?)</description>", re.S)
PART_RE = re.compile(r"<part .*?</part>", re.S)
SLOT_RE = re.compile(r'<feature name="slot" value="([^"]+)"')
ROM_RE = re.compile(r'<rom name="[^"]*" size="(\d+)" crc="([0-9a-fA-F]+)"')

# MAME slot option -> (CartridgeKind variant, image size).
SLOTS = {
    "a800_ossm091": ("OssOneChip", 16384),
    "a800_oss043m": ("OssTwoChip", 16384),
    "a800_oss034m": ("OssTwoChipLegacy", 16384),
    "a800_oss8k": ("OssEightK", 8192),
}


def find_hash_file(start: Path) -> Path | None:
    """Walk up from the repo looking for the vendored MAME hash file."""
    relative = Path("emulators/multi-system/mame/hash/a800.xml")
    for parent in [start, *start.parents]:
        candidate = parent / relative
        if candidate.is_file():
            return candidate
    return None


def parse(xml: str) -> list[tuple[int, str, str]]:
    """Return (crc32, kind, title) for every OSS cartridge."""
    carts: list[tuple[int, str, str]] = []
    for match in SOFTWARE_RE.finditer(xml):
        entry = match.group(0)
        # A title may ship disks beside the cartridge; only the part that
        # carries the slot feature is the cartridge image.
        part = next(
            (
                p.group(0)
                for p in PART_RE.finditer(entry)
                if (s := SLOT_RE.search(p.group(0))) and s.group(1) in SLOTS
            ),
            None,
        )
        if part is None:
            continue
        slot = SLOT_RE.search(part)
        assert slot is not None
        kind, expected_size = SLOTS[slot.group(1)]
        roms = ROM_RE.findall(part)
        if len(roms) != 1:
            raise SystemExit(
                f"{match.group(1)}: expected one <rom>, found {len(roms)}. "
                "The table keys on the whole image, so a split dump needs "
                "handling before it can be included."
            )
        size, crc = roms[0]
        if int(size) != expected_size:
            raise SystemExit(
                f"{match.group(1)}: {slot.group(1)} entry is {size} bytes, "
                f"not {expected_size}."
            )
        title = DESCRIPTION_RE.search(entry)
        carts.append(
            (int(crc, 16), kind, title.group(1).strip() if title else match.group(1))
        )
    return carts


def render(carts: list[tuple[int, str, str]], source: Path) -> str:
    seen: dict[int, str] = {}
    for crc, _, title in carts:
        if crc in seen:
            raise SystemExit(
                f"CRC32 collision between {seen[crc]!r} and {title!r} "
                f"(0x{crc:08X}). The table cannot key on CRC32 alone."
            )
        seen[crc] = title

    # Titles go above their rows: rustfmt aligns trailing comments, which
    # would make the committed file differ from a fresh run.
    rows = "\n".join(
        f"    // {title}\n    (0x{crc >> 16:04X}_{crc & 0xFFFF:04X}, CartridgeKind::{kind}),"
        for crc, kind, title in sorted(carts)
    )
    return f"""//! CRC32s of the Atari 8-bit cartridges built on OSS banking boards.
//!
//! Generated by `tools/a800-oss-cart-types.py` from MAME's `{source.name}`
//! software list (CC0-1.0). Do not edit by hand -- rerun the script.
//!
//! A headerless image whose CRC32 appears here gets the listed board; every
//! other headerless image keeps the plain layout its size implies. See
//! `knowledge/decisions/cart-layout-needs-positive-evidence.md`.

use crate::CartridgeKind;

/// Sorted by CRC32 for `binary_search_by_key`.
pub(crate) const OSS_CRC32: [(u32, CartridgeKind); {len(carts)}] = [
{rows}
];
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--hash-file", type=Path, help="path to MAME's a800.xml")
    parser.add_argument("--out", type=Path, help="write here instead of stdout")
    args = parser.parse_args()

    hash_file = args.hash_file or find_hash_file(Path.cwd().resolve())
    if hash_file is None:
        parser.error(
            "could not find emulators/multi-system/mame/hash/a800.xml above "
            f"{Path.cwd()}; pass --hash-file"
        )
    if not hash_file.is_file():
        parser.error(f"{hash_file} is not a file")

    carts = parse(hash_file.read_text(encoding="utf-8", errors="replace"))
    if not carts:
        raise SystemExit(f"no OSS entries in {hash_file}")

    rendered = render(carts, hash_file)
    if args.out:
        args.out.write_text(rendered, encoding="utf-8")
        print(f"{len(carts)} OSS cartridges -> {args.out}", file=sys.stderr)
    else:
        sys.stdout.write(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
