[package]
name = "runtime-sega-game-gear"
description = "Sega Game Gear machine profiles and runtime constructors"
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
emu198x-shell = { path = "../emu198x-shell", version = "0.7.0" }
machine-sega-master-system = { path = "../machine-sega-master-system", version = "0.7.0" }
runtime-sega-master-system-class = { path = "../runtime-sega-master-system-class", version = "0.7.0" }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
