[package]
name = "runtime-sinclair-zx-spectrum"
description = "Sinclair ZX Spectrum runtime metadata and future family runtime layer"
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
emu198x-shell = { path = "../emu198x-shell" }

[lints]
workspace = true
