[package]
name = "format-amstrad-cpc-cdt"
description = "CDT tape format for the Amstrad CPC"
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
common-tape = { path = "../common-tape", version = "0.20.0" }
format-tzx = { path = "../format-tzx", version = "0.20.0" }

[lints]
workspace = true
