//! Fixture-free proof that the machine starts.
//!
//! The Aquarius needs its manufacturer's ROM to reach a prompt, and that ROM
//! cannot be copied to a public runner. So this asks the weaker question CI
//! *can* answer: put code this project wrote in the ROM socket, and see
//! whether the machine runs it.
//!
//! A pass proves the CPU executed from reset, the ROM is readable where the
//! memory map says it is, screen and colour RAM took their writes, and a
//! frame reached the framebuffer. It does **not** prove the real firmware
//! boots.
//!
//! The image is generated by
//! `test-data/synthetic-firmware/build-synthetic-firmware.py`.
//!
//! The control image here does **not** render black — the Aquarius powers on
//! showing a light blue. What matters is that the two frames differ and that
//! the control never shows the firmware's colour.

use std::path::PathBuf;

use machine_mattel_aquarius::{Aquarius, AquariusRegion};

/// What colour attribute `$66` renders across a screen of spaces.
const BACKGROUND: u32 = 0xFF00_00FF;
/// What the machine shows having run nothing at all.
const POWER_ON: u32 = 0xFF80_80FF;

fn firmware(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../test-data/synthetic-firmware")
        .join(name)
}

fn booted(name: &str) -> Aquarius {
    let rom = std::fs::read(firmware(name)).expect("firmware image");
    let mut machine = Aquarius::new(rom, 0, AquariusRegion::Ntsc);
    for _ in 0..10 {
        machine.run_frame();
    }
    machine
}

#[test]
fn synthetic_firmware_runs_and_floods_the_display() {
    let machine = booted("mattel-aquarius.rom");
    assert!(
        machine
            .framebuffer()
            .iter()
            .all(|&pixel| pixel == BACKGROUND),
        "a screen of spaces under one colour attribute should be uniform"
    );
}

/// The control image spins without touching screen or colour RAM. It still
/// renders — the Aquarius powers on light blue — but never the firmware's
/// colour.
#[test]
fn the_control_image_stays_at_power_on() {
    let machine = booted("mattel-aquarius-control.rom");
    assert!(
        machine.framebuffer().iter().all(|&pixel| pixel == POWER_ON),
        "a machine that ran no firmware should still be at its power-on colour"
    );
    assert_eq!(
        machine
            .framebuffer()
            .iter()
            .filter(|&&p| p == BACKGROUND)
            .count(),
        0,
        "and must not show the firmware's colour"
    );
}
