#!/usr/bin/env python3
"""Generate the committed status pages, or check the committed ones are current.

README, RULES and the acceptance text of many open issues name
`docs/status/current-system-usability.md` and
`docs/status/outstanding-work.md` as authoritative. They had been dead
links long enough that nobody noticed (#825). Restoring them by hand would
restore the thing that decayed: keeping them true meant reconciling four
vocabularies manually, so it stopped happening.

## Why there are no test counts here

Because they would be wrong within a day, and a page that is usually wrong
trains people to stop reading it. Counts live in the evidence ledger that
CI publishes on every run, where being a snapshot is the point.

What is committed is the part that changes only when someone changes it
deliberately: which machines exist, which crate ships each one, which
crates carry evidence for it alone, and where its label and milestone are.
That regenerates from `systems.toml` and the dependency graph without
running a test, which is why CI can check it for drift in seconds rather
than behind a build.

## Drift

`--check` regenerates and compares. A difference fails, and the fix is to
run this and commit the result. Nothing here is edited by hand — an edit
would survive exactly until the next run.
"""

from __future__ import annotations

import argparse
import difflib
import json
import subprocess
import sys
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
REGISTRY = REPO / "docs" / "status" / "systems.toml"
USABILITY = REPO / "docs" / "status" / "current-system-usability.md"
OUTSTANDING = REPO / "docs" / "status" / "outstanding-work.md"

REPO_SLUG = "emu198x/emu198x"
BANNER = (
    "<!-- Generated by scripts/status/render_status.py. Do not edit by hand;\n"
    "     run the script and commit the result. CI fails on drift. -->"
)


def workspace_closures() -> dict[str, set[str]]:
    """Crate -> the workspace crates it transitively depends on.

    Normal dependencies only: a dev-dependency is test scaffolding, and
    following those edges would make every machine depend on every helper.
    """
    raw = subprocess.run(
        ["cargo", "metadata", "--format-version", "1", "--no-deps", "--offline"],
        cwd=REPO,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    meta = json.loads(raw)
    names = {p["name"] for p in meta["packages"]}
    direct = {
        p["name"]: [
            d["name"]
            for d in p["dependencies"]
            if d["name"] in names and d["kind"] is None
        ]
        for p in meta["packages"]
    }

    def closure(root: str) -> set[str]:
        seen: set[str] = set()
        stack = [root]
        while stack:
            crate = stack.pop()
            if crate in seen:
                continue
            seen.add(crate)
            stack.extend(direct.get(crate, ()))
        return seen

    return {name: closure(name) for name in names}


def label_url(label: str) -> str:
    quoted = label.replace(":", "%3A")
    return f"https://github.com/{REPO_SLUG}/issues?q=is%3Aissue+is%3Aopen+label%3A{quoted}"


def milestone_url(title: str) -> str:
    quoted = title.replace(" ", "+").replace("%", "%25")
    return (
        f"https://github.com/{REPO_SLUG}/issues?q=is%3Aissue+is%3Aopen"
        f"+milestone%3A%22{quoted}%22"
    )


def render(systems: list[dict], closures: dict[str, set[str]]) -> tuple[str, str]:
    shipping = sorted({s["crate"] for s in systems})
    reach: dict[str, set[str]] = {}
    for crate in shipping:
        for member in closures[crate]:
            reach.setdefault(member, set()).add(crate)

    rows = []
    for system in sorted(systems, key=lambda s: s["machine_id"]):
        crate = system["crate"]
        own = sorted(c for c in closures[crate] if reach[c] == {crate})
        shared = sorted(c for c in closures[crate] if len(reach[c]) > 1)
        cohabiting = sorted(
            s["machine_id"]
            for s in systems
            if s["crate"] == crate and s["machine_id"] != system["machine_id"]
        )
        rows.append((system, own, shared, cohabiting))

    return _usability(rows), _outstanding(rows)


def _usability(rows) -> str:
    out = [
        BANNER,
        "",
        "# Current system usability",
        "",
        "Every machine this repository ships, and where the evidence for each "
        "one lives. Thirty machines across thirty shipping crates.",
        "",
        "## How to read this",
        "",
        "**Own crates** are reachable from this machine's shipping crate and no "
        "other, so their tests are evidence about this machine. **Shared "
        "crates** are common to several machines — `zilog-z80` passing says "
        "nothing about whether the Einstein boots. A machine with few own "
        "crates has little that can be said about it specifically, however "
        "green the suite looks.",
        "",
        "**There are no test counts on this page.** They would be stale within "
        "a day, and a page that is usually wrong trains people to stop reading "
        "it. Counts are published as the `status-evidence` artifact on every "
        "CI run, where being a snapshot is the point. See "
        "[the evidence decision](../../knowledge/decisions/"
        "evidence-is-what-ran-not-what-was-claimed.md).",
        "",
        "**Milestones are claims, not verification.** A closed "
        "`<machine> 100%` milestone says its issues were closed. It says "
        "nothing about the machine.",
        "",
        "| Machine | Ships from | Own crates | Shared crates | Issues | Milestone |",
        "|---|---|---|---|---|---|",
    ]
    for system, own, shared, cohabiting in rows:
        machine = system["machine_id"]
        if cohabiting:
            machine += " ⚠️"
        out.append(
            f"| `{machine}` | `{system['crate']}` | {len(own)} | {len(shared)} "
            f"| [{system['label']}]({label_url(system['label'])}) "
            f"| [{system['milestone']}]({milestone_url(system['milestone'])}) |"
        )
    out.append("")
    if any(r[3] for r in rows):
        out += [
            "⚠️ Shares a shipping crate with another machine, so neither one's "
            "evidence can be told from the other's.",
            "",
        ]
    else:
        out += [
            "Machine-to-crate is 1:1 across the workspace, so every machine's "
            "own evidence is separable from every other's. It was not always: "
            "the Game Gear shipped from the Master System's crate until #998, "
            "and the two reported identical results because nothing could tell "
            "their tests apart.",
            "",
        ]
    return "\n".join(out)


def _outstanding(rows) -> str:
    exclusions = "+".join(
        f"-label%3A{system['label'].replace(':', '%3A')}" for system, *_ in rows
    )
    cross_cutting = (
        f"https://github.com/{REPO_SLUG}/issues?q=is%3Aissue+is%3Aopen+{exclusions}"
    )
    out = [
        BANNER,
        "",
        "# Outstanding work",
        "",
        "Where the open work is, by the only division the repository actually "
        "encodes: whether an issue names a machine.",
        "",
        "## Cross-cutting work",
        "",
        f"[Open issues carrying no `system:` label]({cross_cutting}) — shared "
        "infrastructure, CPU and chip crates, tooling, release plumbing, and "
        "anything spanning several machines. These are the issues that move "
        "every machine at once, and the ones a per-machine view hides.",
        "",
        "## Future ideas",
        "",
        f"[Open issues labelled `idea`]({label_url('idea')}) — not yet work, "
        "kept so they are not lost.",
        "",
        "## Per-machine work",
        "",
        "One row per machine. The milestone records intent and sequencing; it "
        "is a claim about issues, not about the machine.",
        "",
        "| Machine | Open issues | Milestone |",
        "|---|---|---|",
    ]
    for system, *_ in rows:
        out.append(
            f"| `{system['machine_id']}` "
            f"| [{system['label']}]({label_url(system['label'])}) "
            f"| [{system['milestone']}]({milestone_url(system['milestone'])}) |"
        )
    out += [
        "",
        "## What this page does not do",
        "",
        "**It does not rank machines.** Nothing committed to this repository "
        "encodes priority — not the registry, not the dependency graph, not "
        "the labels. Ordering the table by anything but machine name would be "
        "inventing a claim and presenting it as derived. Roadmap order lives "
        "in `RULES.md` and the decision records, where it is stated by a "
        "person and can be argued with.",
        "",
        "**It does not list issue counts.** They change hourly. Every link "
        "above is a live query, which is both current and honest about being "
        "fetched rather than remembered.",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed pages differ from freshly generated ones",
    )
    args = parser.parse_args()

    systems = tomllib.loads(REGISTRY.read_text())["system"]
    usability, outstanding = render(systems, workspace_closures())
    wanted = {USABILITY: usability, OUTSTANDING: outstanding}

    if not args.check:
        for path, text in wanted.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text + "\n")
            print(f"wrote {path.relative_to(REPO)}")
        return 0

    drifted = []
    for path, text in wanted.items():
        current = path.read_text() if path.exists() else ""
        if current != text + "\n":
            drifted.append((path, current, text + "\n"))

    if not drifted:
        print(f"status pages are current ({len(systems)} machines)")
        return 0

    for path, current, text in drifted:
        print(f"\n{path.relative_to(REPO)} has drifted:")
        diff = difflib.unified_diff(
            current.splitlines(keepends=True),
            text.splitlines(keepends=True),
            fromfile="committed",
            tofile="generated",
        )
        sys.stdout.writelines(diff)
    print(
        "\nRun `python3 scripts/status/render_status.py` and commit the result.",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
