[package]
name = "runtime-commodore-vic-20"
description = "Commodore VIC-20 family metadata and headless runtime wrapper"
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
emu198x-shell = { path = "../emu198x-shell", version = "0.9.0" }
mos-vic-i = { path = "../mos-vic-i", version = "0.9.0" }
machine-commodore-vic-20 = { path = "../machine-commodore-vic-20", version = "0.9.0" }
postcard = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
