[package]
name = "timex-scld"
description = "Timex SCLD (Semi-Custom Logic Device) — TC2048 / TC2068 / TS2068"
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
common-sinclair-zx-spectrum = { path = "../common-sinclair-zx-spectrum", version = "0.22.0" }

[lints]
workspace = true
