[package]
name = "machine-acorn-atom"
description = "Acorn Atom (1980) — 6502 + MC6847 text-mode VDG + 6520 PIA"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
mos-6502 = { path = "../mos-6502" }
mos-pia-6520 = { path = "../mos-pia-6520" }
motorola-vdg-6847 = { path = "../motorola-vdg-6847" }

[lints]
workspace = true
