[package]
name = "nec-upd765a"
description = "NEC µPD765A floppy disk controller — used in the ZX Spectrum +3"
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
common-sinclair-zx-spectrum = { path = "../common-sinclair-zx-spectrum", version = "0.2.0" }
serde = { workspace = true }

[lints]
workspace = true
