[package]
name = "machine-commodore-1541"
description = "Commodore 1541 disk-drive machine substrate"
edition.workspace = true
version = "0.2.0"
license.workspace = true
repository.workspace = true

[dependencies]
common-commodore-iec = { path = "../common-commodore-iec" }
format-commodore-c64-d64 = { path = "../format-commodore-c64-d64" }
mos-6502 = { path = "../mos-6502" }
mos-via-6522 = { path = "../mos-via-6522" }
serde = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
