[package]
name = "gi-ay-3-8910"
description = "General Instrument AY-3-8910 PSG — 3-channel sound + two 8-bit I/O ports (A and B)"
edition.workspace = true
version.workspace = true
publish = false
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }

[lints]
workspace = true
